### ISSUE TITLE
When is the default version for Node.js updated?

### ISSUE THREAD

**Issue by desgovedarska** [cloudfoundry/nodejs-buildpack#100]
Hi guys,
I was wondering what is the strategy used when determining the default runtime version inside the buildpack and how often is it updated. From what I see, Node.js v4.x has been the default for a while, but as we know the maintenance period for version 4 is drawing slowly to it's end (April 2018 if I'm not mistaken). Thank you!

Best Regards,
Dessie

**Comment by dotchev** [comment]
Shouldn't the latest stable version (currently 8) be the default?

**Comment by sclevine** [comment]
Hi @desgovedarska,

Changing a default version has the potential to break existing apps, so we tend to hold off on this until the current default version is "sufficiently old" (without defining what that means...).

Given that we're less than a year away from [Node v4's deprecation date](https://github.com/cloudfoundry/nodejs-buildpack/blob/master/manifest.yml#L26), I think we should bump the default version to Node v8. I'll send out a 30-day breaking change notice soon.

**Comment by desgovedarska** [comment]
Hi @sclevine,
Thank you for the fast answer. Please feel free to close this issue when the update is in place or when you send out the notice. :)

**Comment by leebickmtu** [comment]
I would expect/prefer the oldest supported LTS release to be the default. Which is v6, not v8.
v6 will be in active LTS until April 2018. v8 will be LTS concurrently with it, but I wouldn't require that until v6 drops out of support.

**Comment by sclevine** [comment]
Closing in favor of #114. Sorry for the delay.
