### ISSUE TITLE
Building the buildpack fails

### ISSUE THREAD

**Issue by AHaberl** [cloudfoundry/nodejs-buildpack#102]
I tried to build the buildpack according to the description in the README.

A already failed with the first step: 

```
(cd src/nodejs/vendor/github.com/cloudfoundry/libbuildpack/packager/buildpack-packager && go install) 

     main.go:10:2: cannot find package "github.com/cloudfoundry/libbuildpack/packager" in any of:
        /usr/lib/go-1.6/src/github.com/cloudfoundry/libbuildpack/packager (from $GOROOT)
	/usr/lib/go/src/github.com/cloudfoundry/libbuildpack/packager (from $GOPATH)

```

Could you please help me?

Regards,
Andreas

**Comment by sclevine** [comment]
Your `GOPATH` should be set to the buildpack root. You can source the `.envrc` file at the root of the buildpack to accomplish this, or install direnv to source that file automatically.

**Comment by AHaberl** [comment]
Thanks, now it works :)
