### ISSUE TITLE
Can there be silent mode?

### ISSUE THREAD

**Issue by weymanf** [cloudfoundry/nodejs-buildpack#103]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

cf-cli_6.23.1
api version 2.84.0

What version of the buildpack you are using?

nodejs-buildpack-v1.5.36.zip

If you were attempting to accomplish a task, what was it you were attempting to do?

We were just trying to push our app

What did you expect to happen?

We would like a silent mode because the "building dependency" step was too verbose. We are using a bosh director that apparently had a limit on stdout and our cf push eventually caused our deployment to fail because there were too many logs.

What was the actual behavior?

Our bosh errand failed because there were too many logs.
```
Started running errand > push-apps/0. Failed: Response exceeded maximum allowed length (00:13:41)

Error 450001: Response exceeded maximum allowed length
```

Please confirm where necessary:
* [x ] I have included a log output
* [ x] My log includes an error message

**Comment by sclevine** [comment]
Hi @weymanf,

Can you provide a link to an example app that has excessive output when pushed with the latest version of the buildpack (v1.6.6)?

**Comment by weymanf** [comment]
Sorry for the late response. But we've recently fixed the issue on our side. We were including dev dependencies in our production deploy. However, the amount of noise we generated is still a lot. We can't provide an example of our app because it's private. You can try just cf pushing an app with the postgres and the mariasql npm package; those two packages combined already generate quite a few logs.

To add more. We were doing multiple pushes because we are doing a blue green deploy so it could be very verbose.

**Comment by sclevine** [comment]
Closing this for now. If you can provide an example app that generates excessive output with the latest version of the buildpack, we can re-open the issue and address it.
