### ISSUE TITLE
Instrumenting using AppDynamics is not working

### ISSUE THREAD

**Issue by nkatre** [cloudfoundry/nodejs-buildpack#112]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
`cf version 6.23.1+a70deb38f.2017-01-13`

What version of the buildpack you are using?
Latest nodejs online buildpack

If you were attempting to accomplish a task, what was it you were attempting to do?
Instrumenting application using NodeJs agent of appdynamics

What did you expect to happen?
See the app on AppDynamics controller

What was the actual behavior?
The appdynamics nodejs process was not working

`Steps to reproduce`
1. Push sample node js app.
2. Bind to appdynamics node js service
3. Restage the application

`Logs`
Logs do not show any error message

Please confirm where necessary:
* [ ] I have included a log output
* [* ] My log includes an error message
* [* ] I have included steps for reproduction

**Comment by sclevine** [comment]
@nkatre We suspect that a change in the agent has broken its integration with the buildpack. We currently have no way to test for regressions like this. Can you provide us with a permanent AppDynamics account that we can use in our pipeline to test this integration?

**Comment by nkatre** [comment]
@sclevine I think I know whats causing it to fail to start appdynamics agent. Its trying to run a proxy service but its unable to do so because of insufficient rights to execute it. Do you know where can i run some commands to give execution rights in the /tmp directory of the container ?  I am checking for a place where i can specify 2-3 commands that the build pack needs to run in the runtime container prior to the app starting.

**Comment by nkatre** [comment]
@sclevine Also, I am working with the team, to get the appdynamics account provisioned for testing purposes

**Comment by sclevine** [comment]
Thanks @nkatre!

How about here: https://github.com/cloudfoundry/nodejs-buildpack/blob/master/profile/appdynamics-setup.sh#L4-L5

**Comment by nkatre** [comment]
The issue was appd service created using cups was not getting identified. This PR would fix it https://github.com/cloudfoundry/nodejs-buildpack/pull/106
Closing this issue
