### ISSUE TITLE
Support for Node 8.9.0 LTS

### ISSUE THREAD

**Issue by john681611** [cloudfoundry/nodejs-buildpack#113]
What version of the buildpack you are using? 1.6.10

If you were attempting to accomplish a task, what was it you were attempting to do?
use Node LTS 8.9.0

What did you expect to happen?
Build Pack to successfully deploy.

What was the actual behaviour?
```
Downloading app package...
Downloaded app package (870.3K)
Staging...
-----> Download go 1.9.1
-----> Running go build supply
-----> Nodejs Buildpack version 1.6.10
-----> Installing binaries
       engines.node (package.json): 8.9.0
       engines.npm (package.json): 5.5.1
       **ERROR** Unable to install node: no match found for 8.9.0 in [7.10.0 7.10.1 4.8.4 6.11.4 8.7.0 8.8.0 6.11.5 4.8.5]
Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223
Destroying container
Successfully destroyed container
```

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by sclevine** [comment]
This is already on the `develop` branch, and will go out in the next release: 5870c7100a5f246e9c381ab60031917a17bfd8c7 [#152449876](https://www.pivotaltracker.com/story/show/152449876)

All new supported versions of Node.js are automatically included in the buildpack by our pipeline. If you believe that we've missed a version for some reason, please check the backlog and `develop` branch to check the status.

**Comment by john681611** [comment]
Cool thanks
