### ISSUE TITLE
Release v1.6.11

### ISSUE THREAD

**Issue by paulbeattie** [cloudfoundry/nodejs-buildpack#115]
What version of the buildpack you are using?
1.6.11/016456be1c61d84a0ca444ccf3fae270c4b561d3

If you were attempting to accomplish a task, what was it you were attempting to do?
Stable deployment

What did you expect to happen?
Specifying 1.6.11 would give me the latest buildpack version

What was the actual behavior?
Release is not tagged properly so this doesn't work.

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by sclevine** [comment]
The latest buildpack version is actually 1.6.10. See: https://github.com/cloudfoundry/nodejs-buildpack/releases

The next buildpack version is merged to master before the official release happens.

**Comment by paulbeattie** [comment]
@sclevine the last commit to master includes a bump in version. Is this not it?

**Comment by paulbeattie** [comment]
Now tagged. I'll close this off.

**Comment by sclevine** [comment]
Sorry, missed your follow-up question. Master is updated with the version bump before the release is officially cut/tagged.
