### ISSUE TITLE
Node version 8.8.0 is not allowed even though its listed in the release notes

### ISSUE THREAD

**Issue by bigorangemachine** [cloudfoundry/nodejs-buildpack#116]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

`cf version 6.32.0+0191c33d9.2017-09-26`

What version of the buildpack you are using?

`https://github.com/cloudfoundry/nodejs-buildpack` (Current?)

If you were attempting to accomplish a task, what was it you were attempting to do?

cf push a node instance (node version 8.8.0)

What did you expect to happen?

To finish successfuly

What was the actual behavior?

Can't find node version 8.8.0

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

```Creating container
Successfully created container
Downloading build artifacts cache...
Downloading app package...
Downloaded app package (156.1K)
Downloaded build artifacts cache (13.5M)
-----> Download go 1.9.1
-----> Running go build supply
-----> Nodejs Buildpack version 1.6.12
-----> Installing binaries
       engines.node (package.json): 8.8.0
       engines.npm (package.json): 5.4.2
       **ERROR** Unable to install node: no match found for 8.8.0 in [4.8.5 6.11.5 7.10.0 7.10.1 8.9.0 6.12.0 4.8.6 9.1.0 8.9.1 9.2.0]
Failed to compile droplet: Failed to run all supply scripts: exit status 14
Exit status 223
Stopping instance 13d271a8-9948-4bf0-9d6c-072ad4fc0002
Destroying container
Successfully destroyed container

FAILED
Error restarting application: BuildpackCompileFailed
```

Reproduction:

Setup a node project locally (package.json) by setting the engines to ```"engines": {
    "node": "8.8.0",
    "npm": "5.4.2"
  }```

cf login
cf push

**Comment by sclevine** [comment]
To strike a balance between security and ease of migration to newer Node.js versions, we only provide the last two (backwards-compatible) patch versions of each major line of Node.js in the buildpack.

I recommend that you modify your package.json file to use the latest 8.x.x release, instead of a particular patch release.

**Comment by bigorangemachine** [comment]
No problem!

Was just trying to flag the mismatch between docs & implementation
