### ISSUE TITLE
error in using the latest nodejs buildpack

### ISSUE THREAD

**Issue by royling** [cloudfoundry/nodejs-buildpack#117]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
{
   "name": "",
   "build": "",
   "support": "https://support.pivotal.io",
   "version": 0,
   "description": "",
   "authorization_endpoint": "",
   "token_endpoint": "",
   "min_cli_version": "6.23.0",
   "min_recommended_cli_version": "6.23.0",
   "api_version": "2.82.0",
   "app_ssh_endpoint": "",
   "app_ssh_host_key_fingerprint": "",
   "app_ssh_oauth_client": "ssh-proxy",
   "routing_endpoint": "",
   "doppler_logging_endpoint": "",
   "user": ""
}
cf version 6.33.1+c77e55743.2017-12-15

What version of the buildpack you are using?
the latest nodejs buildpack: v1.6.13
In manifest.yml:
```yml
buildpack: https://github.com/cloudfoundry/nodejs-buildpack.git#v1.6.13
```

If you were attempting to accomplish a task, what was it you were attempting to do?
`cf push`

What did you expect to happen?
the latest buildpack is successfully applied.

What was the actual behavior?
see the error logs:
Creating container
Successfully created container
Downloading app package...
Downloaded app package (732B)
Downloading build artifacts cache...
Downloaded build artifacts cache (648.2K)
Staging...
-----> Download go 1.9.1
Failed to compile droplet: Failed to run all supply scripts: exit status 60
Exit status 223
Staging failed: STG: Exited with status 223
Stopping instance 6cd6ac80-f360-4515-85b8-4b2dc102016d
Destroying container
Successfully destroyed container

FAILED
Error restarting application: BuildpackCompileFailed

PS: I am using a local/private PCF instance, and behind a corporate firewall. Is this an issue related with network/firewall?

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by royling** [comment]
Using the buildpack name (ie. `nodejs_buildpack`) in `manifest.yml` worked though, I intend to use the latest nodepack for a new node version.
```
$ cf buildpacks | grep node
nodejs_buildpack                       2          true      false    nodejs_buildpack-cached-v1.6.3.zip
```

**Comment by sclevine** [comment]
Hi @royling, sorry for the delay.

It appears that the online version of buildpack is not able to download Go to compile itself in your environment. You could install or host an offline version of the buildpack, or you modify your network settings to allow downloads from buildpacks.cloudfoundry.org. I suspect this is already done for github, because PCF is able to download the buildpack itself from github.

**Comment by royling** [comment]
@sclevine you're right. I already got the buildpack of the required version. Closing this issue, thanks!
