### ISSUE TITLE
npm install from public git repo not working from buildpack

### ISSUE THREAD

**Issue by nayanchandni** [cloudfoundry/nodejs-buildpack#118]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
6.28.0

What version of the buildpack you are using?
1.6.14

I have a git repo behind corporate proxy listed in the package.json of my project which I am able to install via a simple npm install , but from within the buildpack it fails when it reads from the package.json and giving the following error.

Starting app predix-io-set-npm in org predix-io / space dev as predix-experience-deployer...
-----> Download go 1.9.1
-----> Running go build supply
-----> Nodejs Buildpack version 1.6.14
-----> Installing binaries
       engines.node (package.json): 6.x.x
       engines.npm (package.json): unspecified (use default)
-----> Installing node 6.12.2
       Download [https://buildpacks.cloudfoundry.org/dependencies/node/node-6.12.2-linux-x64-e54a0511.tgz]
       Using default npm version: 3.10.10
-----> Installing yarn 1.2.1
       Download [https://buildpacks.cloudfoundry.org/dependencies/yarn/yarn-v1.2.1-a16106e2.tar.gz]
       Installed yarn 1.2.1
-----> Creating runtime environment
       PRO TIP: It is recommended to vendor the application's Node.js dependencies
       Visit http://docs.cloudfoundry.org/buildpacks/node/index.html#vendoring
       NODE_ENV=production
       NODE_HOME=/tmp/app/.cloudfoundry/0/node
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
-----> Restoring cache
       Skipping cache restore (no previous cache)
-----> Building dependencies
       Installing node modules (package.json)

npm ERR! Linux 4.4.0-64-generic
npm ERR! argv "/tmp/app/.cloudfoundry/0/node/bin/node" "/tmp/app/.cloudfoundry/0/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/app/.npmrc" "--cache" "/tmp/app/.npm"
npm ERR! node v6.12.2
npm ERR! Cloning into bare repository '/tmp/app/.npm/_git-remotes/git-ssh-git-github-build-ge-com-Predix-Experience-predix-io-utilities-git-federated-uaa-64bbaadb'...
npm ERR! ssh: Could not resolve hostname github.build.ge.com: Name or service not known
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! npm  v3.10.10
npm ERR! code 128

My question is if this is because of any proxy setup needed for the buildpack and how can I vendor just one dependency?

Thanks!

**Comment by dgodd** [comment]
@nayanchandni Given the error is a hostname error, my guess would be that the staging machines can't reach your npm repository. 

I assume that when you say you can use `npm install`, you mean from your machine, and not from inside the cf foundation?

The answer may be as simple as setting the environment variable `HTTP_PROXY` and/or `HTTPS_PROXY`. Assuming the foundation can access the proxy, try setting those to the proxy

**Comment by nayanchandni** [comment]
During the build process, I do set the htttp_proxy and https_proxy variables. Does the case matter?

And yes the npm install is local on my machine. but the install is trying to reach a github repo and not the npm registry itself.

Also, can I vendor just one dependency and let the others be installed at runtime?

**Comment by dgodd** [comment]
From memory the npm vendoring is all or nothing. The case may matter for
http_proxy try both (I think upper case)

**Comment by LeoK80** [comment]
if the repo is a private repo it might also be an access issue. make sure to access with a token or other valid mechanism.

**Comment by sclevine** [comment]
Hi @nayanchandni, were you able to resolve this issue?

**Comment by nayanchandni** [comment]
@sclevine yes it was private repo that needed cache cleaning.
