### ISSUE TITLE
Incorrect build instructions

### ISSUE THREAD

**Issue by aclissold** [cloudfoundry/nodejs-buildpack#12]
The README states to use `bin/package [ online | offline ]` to compile this buildpack, but there is no `package` command in `bin/` anymore.

**Comment by jchesterpivotal** [comment]
It's wrong there and in the docs as well. We had [an identical report on ruby buildpack](https://github.com/cloudfoundry/ruby-buildpack/issues/29) which was [also entered into Tracker](https://www.pivotaltracker.com/story/show/85807806).

As with that case, when we have updated the README I will loop back and close this issue. I'm sorry for the confusion.

**Comment by jchesterpivotal** [comment]
We've updated the README, so I am going to close this issue.
