### ISSUE TITLE
yarn update needed

### ISSUE THREAD

**Issue by LeoK80** [cloudfoundry/nodejs-buildpack#123]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
cf version 6.26.0-nimbus+19d68e0.2017-06-01

What version of the buildpack you are using? 
v1.6.15

If you were attempting to accomplish a task, what was it you were attempting to do?
building nodejs project that utilises Yarn v 1.3.2
current supported Yarn in latest release (Yesterday) only goes up to v 1.2.1 of Yarn

What did you expect to happen?
Expected the latest release also to include updated Yarn support

What was the actual behavior?
It doesn't support Yarn v 1.3.2

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by dgodd** [comment]
Hi @LeoK80, we held off on yarn v1.3.2 due to https://github.com/yarnpkg/yarn/issues/4885 . We are awaiting the next version, which at the minute looks like it will be v1.4.0

Is there any reason you need 1.3.2 specifically?

**Comment by LeoK80** [comment]
hi @dgodd . We have several changes going on simultaneously which include upgrading to latest LTS for nodejs, using the latest nodejs buildpack and bumping the Yarn version. 
We'll stick to Yarn v1.2.1 and await your new release after Yarn has released their fix for the HTTP_PROXY issues. Cheers

**Comment by sclevine** [comment]
Closing this as resolved. We will include the first release of yarn that fixes the proxy bypass issue.
