### ISSUE TITLE
Install imagemagick

### ISSUE THREAD

**Issue by ramzes13** [cloudfoundry/nodejs-buildpack#128]
Hello, 

How can I install/use [imagemagick](https://www.imagemagick.org/script/index.php) on this buildpack

This is a dependence from [gm](https://www.npmjs.com/package/gm)

Thank you in advance.

**Comment by sclevine** [comment]
imagemagick is already present in the rootfs

**Comment by ramzes13** [comment]
Thank you it seems to work !
