### ISSUE TITLE
Add support for io.js from upstream repo

### ISSUE THREAD

**Issue by cgfrost** [cloudfoundry/nodejs-buildpack#13]
The Heroku Node Buildpack added support for io.js with this pull request on the 14th January.

https://github.com/heroku/heroku-buildpack-nodejs/pull/181 

Please can you update from upstream at Heroku to enable io.js support on Cloud Foundry. 
Thanks.

**Comment by jtarchie** [comment]
At this time, we have to discuss the testing strategy of `io.js`. Since it is brand new, most of us don't have any experience with it. It is a hard fork from `node` at a particular version, but there are differences in runtime and such.

Our discussion includes what integration tests we want to put around it. If we can easily take our `node` tests and just use them for `io.js`, then we have a good place to start.

Most importantly product needs to prioritize this for us. We'll keep this ticket updated.

**Comment by cgfrost** [comment]
Thanks for the info. My instinct is that you should just reuse your existing integration tests, there is no need to test new language features etc... as that's not part of the buildpack. The only change that should be required to test applications (or any application) wanting to use iojo is to update the ```package.json``` file to specify an ```iojo``` engine instead of a ```node``` one and the merge from Heroku should take care of all of that.

**Comment by jchesterpivotal** [comment]
I'm not sure it'll be completely straightforward. The initial io.js patch [refers to a resolution service on Heroku](https://github.com/heroku/heroku-buildpack-nodejs/commit/0048d0ca4fd36f9dbfa4aeaadbbeca7f166c02e7#diff-cbea48db73996bd0b8adcff9b6b7fbd2R96). 

To support the cached (offline) buildpack we'd need to replicate that functionality in `lib/version_resolver.js` and shunt the request to semver.herokuapp.com to it.

**Comment by MarkKropf** [comment]
@jtarchie @flavorjones Can we take a new look at this? It doesn't look like a lot has changed on their end to support it, we may be able to get around not pulling latest from semver and instead use latest we package in the skinny buildpack. 

/cc @stubbornella

**Comment by stubbornella** [comment]
We'd love to start using and testing on io.js on CF. Promises on io will throw exceptions all the way up, where as node 10 swallows them. This has been problematic.

**Comment by rdy** [comment]
Yea I'd also like to see support for io. The two forks are probably going to be merging back, but its likely that most of the changes will be coming from io. If we want to stay current its probably good to have support now. It isn't clear when they will reconcile but io seems to be where all the new development is happening now.

**Comment by flavorjones** [comment]
I've scheduled work on this -- see https://www.pivotaltracker.com/story/show/88227116 for details.

**Comment by cgfrost** [comment]
This might not be relevant now, seems that iojs is planning to merge back in to Node http://www.theregister.co.uk/2015/06/15/nodejs_iojs_project_merger/

**Comment by flavorjones** [comment]
@mhoran says:

> We verified that the Node.JS and io.js code bases will be merging. The io.js project will become Node.js. Currently the merge is still in process, and the official site still links to Joyent's source. However, this should be pointing to io.js at some point in the "near" future.
> We modified the buildpack to use a binary produced from the io.js source, and brats tests passed. We're not going to make the required changes to binary-builder at this point, as everything is a moving target at the moment.
> See https://nodejs.org/foundation/#index_md_timeline for an outdated timeline
