### ISSUE TITLE
v1.6.21 breaks yarn install when deploying

### ISSUE THREAD

**Issue by sinnott74** [cloudfoundry/nodejs-buildpack#131]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

What version of the buildpack you are using?
Latest (1.6.21)

If you were attempting to accomplish a task, what was it you were attempting to do?
Deploy from TravisCI to Bluemix

What did you expect to happen?
Application to deploy & start

What was the actual behavior?
Deployment failed when starting application due to node modules being missing

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

Average yarn install time went from 20+ seconds on v1.6.20  to <2 seconds v1.6.21. Application is using yarn workspaces & to system link various packages in a monorepo FYI (saw it a mention in the changelogs). 

Reverting back to v1.6.20 fixed the deployment

**Comment by sclevine** [comment]
Hi @sinnott74,

Can you provide a sample app that demonstrates the change in behavior that you're seeing?

**Comment by sinnott74** [comment]
If you compare the yarn install time during the deploy phase of each travis build

**v1.6.20**
```
   yarn install v1.5.1
   [1/4] Resolving packages...
   [2/4] Fetching packages...
   info fsevents@1.1.3: The platform "linux" is incompatible with this module.
   info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
   [3/4] Linking dependencies...
   [4/4] Building fresh packages...
   Done in 31.50s.
```
**Done in 31.50s.**

**v1.6.21**
```
   yarn install v1.5.1
   [1/4] Resolving packages...
   [2/4] Fetching packages...
   [3/4] Linking dependencies...
   [4/4] Building fresh packages...
   Done in 0.79s.
```
**Done in 0.79s.**

**Comment by sinnott74** [comment]
```
cf curl /v2/info && cf version
{
   "name": "Bluemix",
   "build": "270028",
   "support": "http://ibm.biz/bluemix-supportinfo",
   "version": 0,
   "description": "IBM Bluemix",
   "authorization_endpoint": "https://login.ng.bluemix.net/UAALoginServerWAR",
   "token_endpoint": "https://uaa.ng.bluemix.net",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "api_version": "2.92.0",
   "app_ssh_endpoint": "ssh.ng.bluemix.net:2222",
   "app_ssh_host_key_fingerprint": "c7:1f:89:2a:62:3b:78:a9:08:c9:33:81:fb:39:26:da",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.ng.bluemix.net:443",
   "user": "fca47d20-8a91-44df-aab0-a8b76c9552c0"
}
cf version 6.22.2+a95e24c-2016-10-27
```

**Comment by sclevine** [comment]
Can you let us know if 1.6.22 fixes the issue?

**Comment by sinnott74** [comment]
It does!
