### ISSUE TITLE
Webpack not found on v1.6.21

### ISSUE THREAD

**Issue by madamkiwi** [cloudfoundry/nodejs-buildpack#135]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
PWS (api version 2.106.0), cf-cli version 6.35.2

What version of the buildpack you are using?
1.6.21

If you were attempting to accomplish a task, what was it you were attempting to do?
pushing an app

What did you expect to happen?
success (works on nodejs-buildpack version 1.6.20)

What was the actual behavior?
```
[STG/0] [ERR] sh: 1: webpack: not found
[STG/0] [ERR] error An unexpected error occurred: "Command failed.
[STG/0] [ERR] Exit code: 127
```

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by sclevine** [comment]
Hi @madamkiwi,

Thanks for the report! Can you provide a sample app to help us reproduce the issue?

**Comment by madamkiwi** [comment]
Hi @sclevine, I think I may have figured out the issue, my package.json is running shell commands using a relative path but the current working directory seems to have changed in nodejs_buildpack v1.6.21, causing the shell command to fail.  Since this is completely different from the issue title, feel free to close this issue.
