### ISSUE TITLE
js-bson: Failed to load c++ bson extension, using pure JS version

### ISSUE THREAD

**Issue by anton-ego-ge** [cloudfoundry/nodejs-buildpack#136]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

{
   "name": "",
   "build": "",
   "support": "https://support.run.pivotal.io",
   "version": 0,
   "description": "Cloud Foundry sponsored by Pivotal",
   "authorization_endpoint": "https://login.run.pivotal.io",
   "token_endpoint": "https://uaa.run.pivotal.io",
   "min_cli_version": "6.22.0",
   "min_recommended_cli_version": "latest",
   "api_version": "2.107.0",
   "app_ssh_endpoint": "ssh.run.pivotal.io:2222",
   "app_ssh_host_key_fingerprint": "e7:13:4e:32:ee:39:62:df:54:41:d7:f7:8b:b2:a7:6b",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.run.pivotal.io:443",
   "routing_endpoint": "https://api.run.pivotal.io/routing"
}
cf version 6.36.0+eca59e5b8.2018-04-02

What version of the buildpack you are using?

 buildpack: https://github.com/cloudfoundry/nodejs-buildpack

If you were attempting to accomplish a task, what was it you were attempting to do?

I was pushing my app( cf push ) and it fails to start

What did you expect to happen?

I was expecting app to upload and run

What was the actual behavior?

App uploaded but failed to run

Can you provide a sample app?

Yes

Please confirm where necessary:
* [X] I have included a log output
* [X] My log includes an error message
* [X] I have included steps for reproduction
[error.log](https://github.com/cloudfoundry/nodejs-buildpack/files/1887579/error.log)

**Comment by sclevine** [comment]
It looks like your application code expects the app to be bound to a MongoDB service called `mongolab`:
```
   2018-04-08T18:54:02.70+0400 [APP/PROC/WEB/0] ERR 	url = vcap_services['mongolab'][0].credentials.uri;
   2018-04-08T18:54:02.70+0400 [APP/PROC/WEB/0] ERR 	                               ^
   2018-04-08T18:54:02.70+0400 [APP/PROC/WEB/0] ERR TypeError: Cannot read property '0' of undefined
```
I suspect this is the error that is preventing your app from starting.

**Comment by anton-ego-ge** [comment]
Thanks, @sclevine ! That was an issue. I used "cf env APPNAME" to get a correct name of service:
System-Provided:
{
 "VCAP_SERVICES": {
  "mlab":
