### ISSUE TITLE
Anyway to make the bundle work behind http proxy?

### ISSUE THREAD

**Issue by datianshi** [cloudfoundry/nodejs-buildpack#14]
http://stackoverflow.com/questions/20688914/bundle-install-fails-because-of-git-protocol

I run into the above issue, when I run "bundle" behind the http proxy.

**Comment by jtarchie** [comment]
@datianshi `bundle` is Ruby specific not nodejs. Could you please open an issue on the [Ruby](https://github.com/cloudfoundry/ruby-buildpack) buildpack. Thanks

**Comment by datianshi** [comment]
This is project related and can be enhanced.

If you read the stackflow above. You can make the gem as

gem 'machete', git: 'http://github.com/cf-buildpacks/machete', branch: 'master'

So the regular http proxy will work. The problem is here is using git proxy. 

This helps people work in corporate, which everything goes through an http proxy

-Shaozhen
A Pivotal employee

**Comment by joefitzgerald** [comment]
@jtarchie I believe what @datianshi is trying to convey is that he is having an issue _modifying the nodejs buildpack_ (which _is written in Ruby_). So his issue is not with pushing a Ruby app that _uses_ the Ruby buildpack - his issue is related to development of the nodejs buildpack.

This is the line in question: https://github.com/cloudfoundry/nodejs-buildpack/blob/e5e2c6b80626918acdacfaf22671287fe55ce9b9/cf.Gemfile#L5 (note the next line would be affected by the same issue also).

**Comment by jtarchie** [comment]
Thanks for the clarification. Let me discuss with the team, but a pull request would probably be a faster turn around.

**Comment by flavorjones** [comment]
This should be addressed as soon as we merge #15, which is being tracked here: https://www.pivotaltracker.com/story/show/90318946
