### ISSUE TITLE
"Ensure app directory is not modified in supply phase" is breaking the deployment

### ISSUE THREAD

**Issue by adrai** [cloudfoundry/nodejs-buildpack#142]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
```
{
   "name": "",
   "build": "",
   "support": "https://developer.swisscom.com/contact",
   "version": 0,
   "description": "Cloud Foundry provided by Swisscom",
   "authorization_endpoint": "https://login.test-137.appcloud.swisscom.com",
   "token_endpoint": "https://uaa.test-137.appcloud.swisscom.com",
   "min_cli_version": "6.24.0",
   "min_recommended_cli_version": "latest",
   "api_version": "2.84.0",
   "app_ssh_endpoint": "ssh.test-137.appcloud.swisscom.com:2222",
   "app_ssh_host_key_fingerprint": "eb:51:e0:9e:f9:45:38:1b:8a:55:a5:ae:9f:89:ae:50",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.test-137.appcloud.swisscom.com:443"
}
cf version 6.23.1+a70deb38f.2017-01-13
```

What version of the buildpack you are using?
v1.6.22 (but stick on v1.6.20)

If you were attempting to accomplish a task, what was it you were attempting to do?
I want to execute a preInstall and postInstall script that modifies some files.
Since this change this is impossible: https://www.pivotaltracker.com/n/projects/1042066/stories/155602498
https://github.com/cloudfoundry/nodejs-buildpack/commit/8c515ebdc54a1e9ab46d4deb615a40bcdc8f312c

What did you expect to happen?
Same behaviour as v1.6.20

**Comment by sclevine** [comment]
See: https://github.com/cloudfoundry/nodejs-buildpack/issues/140#issuecomment-383607494

You should be able to use `$NODE_PATH` to find your `node_modules` directory. Note that this change only applies to apps that aren't vendored.

We generally do not guarantee that each buildpack version produces the exact same changes to the app directory -- only that the app behaves the same.

In the future, we'll communicate significant changes to the app directory in the Node.js buildpack more widely, given that build-time hooks in the app directory via package.json are common.

**Comment by adrai** [comment]
`$NODE_PATH` seems not to be an option for my use case...
I have some scripts that modifies files during preinstall and postinstall time...

**Comment by sclevine** [comment]
Can you provide more details? What files are you trying to change? If those files are in `node_modules`, why can't you use `$NODE_PATH` to find them?

**Comment by adrai** [comment]
I have no problem in finding the node_modules...
in my scripts i modify/add/remove some files in my app directory...

**Comment by sclevine** [comment]
Ah, I see what you mean. We now fail staging if any files in the app directory change. We will likely revert that change in the next release of the buildpack.

**Comment by adrai** [comment]
fyi: v1.6.22 seems better than v1.6.21
