### ISSUE TITLE
Clarification regarding 'node_modules' location

### ISSUE THREAD

**Issue by petar-iv** [cloudfoundry/nodejs-buildpack#145]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

```
api_version: 2.107.0
cf version: 6.30.0
```

What version of the buildpack you are using?

`v1.6.23`

If you were attempting to accomplish a task, what was it you were attempting to do?

```
Deploy an application without vendored dependencies,
start the app through a dependency
(https://github.com/petar-iv/demo-app/blob/master/package.json#L8).
```

What did you expect to happen?

`The application to start successfully (as it does with v1.6.21 of the buildpack).`

What was the actual behavior?

```
Application does not start. Error is:

 module.js:478
     throw err;
     ^
 Error: Cannot find module '/home/vcap/app/node_modules/demo-package/file.js'
     at Function.Module._resolveFilename (module.js:476:15)
     at Function.Module._load (module.js:424:25)
     at Module.runMain (module.js:611:10)
     at run (bootstrap_node.js:387:7)
     at startup (bootstrap_node.js:153:9)
     at bootstrap_node.js:500:3
```

Can you provide a sample app?

https://github.com/petar-iv/demo-app

Steps to reproduce:
1. `git clone https://github.com/petar-iv/demo-package.git`
2. `cf push reproduce-with-1-6-23`

I see there are changes to where the `node_modules` directory is located (as explained in [that issue](https://github.com/cloudfoundry/nodejs-buildpack/issues/140#issuecomment-382097703)). These changes currently affect my scenario. Does that mean that my scenario will no longer be supported and we should notify our customers to use `$NODE_PATH` instead of the current approach? Or there will be a fix with which changes to application code (the `start command`) will not be needed? Since the major version of the buildpack is not changed, I'd assume that this incompatible behavior is something that has appeared after the release.

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by petar-iv** [comment]
A drawback of always using `node $NODE_PATH/demo-package/file.js` as a start command would be that developers working locally on Windows cannot start the application (without code changes) with just `npm start` (because of the `$NODE_PATH` part), but will need to execute the command `node ...` manually. Which might not be handy if there are several command-line arguments to the Node.js program.

**Comment by sclevine** [comment]
The expected behavior is:
1. If you push your app with `node_modules` vendored in the app root, you can expect `node_modules` to be present in the app root at launch, and `NODE_PATH` to be set to `/home/vcap/app/node_modules`.
2. If you push your app without vendoring a `node_modules` directory, the buildpack will install `node_modules` somewhere else and set `NODE_PATH` to that location.

Can you provide more detail about your use case? Why is the entrypoint to your app in `node_modules` instead of in your app source?

**Comment by petar-iv** [comment]
In our case we provide frameworks which allow users to create and deploy applications providing only some configurations without writing any JavaScript code. Since the application does not have a `.js` file, the `start command` references a script from its `node_modules` (as the app depends to one of the frameworks).

**Comment by Emilius1** [comment]
Hi sclevine,
This is pure incompatible change of the buildpack. Wonder why you don't follow https://semver.org/ guideline.
In package.json it used to work with 
"start": "node node_modules/myapp.js"
Now it has to be:
"start": "node $NODE_PATH/myapp.js"
Plus the challenge with MS Windows that peter-iv mentioned makes it even more hard to understand reasons behind that change.
Can you shed some light behind this change between v1.6.21 and v1.6.22?
Thanks

**Comment by sclevine** [comment]
This change was actually a bug fix. In versions before v1.6.22, the buildpack was modifying the app directory in the `/bin/supply` phase, which is explicitly prohibited by the buildpack<->platform contract.

We've never documented that the buildpack would create `node_modules` in the app directory if the app was pushed without it, and node has a convention (`$NODE_PATH`) for specifying the location of the `node_modules` directory.  We cannot guarantee the app directory looks exactly the same post-staging for each new buildpack release. In general, we use semver to communicate breaking changes in documented buildpack features, not in undocumented implementation details that some apps may be relying on.

That said, we realize that Node.js app developers may expect `node_modules` to always be generated at the app root, and may not realize that the location may be specified in `$NODE_PATH` instead. We're looking into creating a symlink between `app/node_modules` and the new location at launch.

**Comment by Shingaz** [comment]
@sclevine This breaks the installation of [local packages](https://docs.npmjs.com/files/package.json#local-paths). In this case npm creates a symlink in the `node_modules` with the path provided in the `package.json`.  If the buildpack installs the node_modules "somewhere else" the dependency cannot be resolved at runtime because the target path is now wrong.

```json
// package.json
{
  "name": "example",
  "dependencies": {
    "local": "./local"
  }
}
```

```js
// index.js
import something from 'local' <--  Error: Cannot find module 'local'
```

```bash
$ ls /home/vcap/app
index.js
local/

$ echo $NODE_PATH
/home/vcap/deps/0/node_modules

$ readlink $NODE_PATH/local
../local
```
As you can see `/home/vcap/deps/0/node_modules/../local` does not resolve to `/home/vcap/app/local`
