### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by elior-snps** [cloudfoundry/nodejs-buildpack#146]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
Not relevant

What version of the buildpack you are using?
Not relevant

If you were attempting to accomplish a task, what was it you were attempting to do?
Not relevant

What did you expect to happen?
Not relevant

What was the actual behavior?
Not relevant

Can you provide a sample app?
Not relevant

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

I want to implement a new nodejs-buildpack, there is not enough documentation in this repo for the relevant hooks and mechanisms. Please advise

**Comment by sclevine** [comment]
Are you trying to implement a new buildpack from scratch, or make changes to this buildpack? If you're trying to make changes to this buildpack, could you describe what you're trying to do?

**Comment by elior-snps** [comment]
I've already managed to write the build pack. 
I had to add environment variables and a new npm dependency (download the depdency from external server, not npm server)

**Comment by sclevine** [comment]
Glad you figured it out. Feel free to reach out if you have additional questions.
