### ISSUE TITLE
Support `.nvmrc` file as an alternative to `engine.version` setting in `package.json`

### ISSUE THREAD

**Issue by berlin-ab** [cloudfoundry/nodejs-buildpack#148]
We've been using Node Version Manager (https://github.com/creationix/nvm) to manage node versions for our project. I'd like to not have to manage the version of Node in two places for when we deploy to Cloud Foundry. It would be nice if the CF Node Buildpack supported both `.nvmrc` and `package.json` configuration.

`package.json`
```
{
  "engines": {
    "node": "10.4.1"
  }
}
```

`.nvmrc`
```
10.4.1
```

**Comment by sclevine** [comment]
Thanks for the feature request. This looks simple enough to implement, and I understand the value. I'll prioritize this soon, but it may take some time before we can start working on it.

**Comment by sclevine** [comment]
This feature is now available on `develop` and will go out in the next release. Apologies for the long turn-around.

**Comment by tomratcliffe** [comment]
Hi, thanks for implementing this!

Looking at the docs on cloudfoundry.org, it doesn't mention this functionality (at the time of writing) - will this be updated, or can I open a PR somewhere to update this for you?

https://docs.cloudfoundry.org/buildpacks/node/index.html#runtime

Thanks!

**Comment by tomratcliffe** [comment]
Hi, has this functionality been released yet? I can't see it in the documentation - thanks!

**Comment by cyrilchapon** [comment]
...or just comment in here in `nvm` package to follow the (standard ?) `engines` field :

https://github.com/nvm-sh/nvm/issues/651
