### ISSUE TITLE
Failed to compress droplet filesystem: signal: broken pipe

### ISSUE THREAD

**Issue by AlexOwen** [cloudfoundry/nodejs-buildpack#150]
**What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?**

name: Bluemix,
build: 270030,
api_version: 2.92.0
cf version 6.36.2+18ceab10f.2018-05-16

**What version of the buildpack you are using?**

Latest

**If you were attempting to accomplish a task, what was it you were attempting to do?**

Deploy an application using deploy stage of delivery pipeline.

**What did you expect to happen?**

The app to deploy.

**What was the actual behaviour?**

The deploy failed repeatedly with an error of "Failed to compress droplet filesystem: signal: broken pipe".

The code was the same as previous deployments and successfully deployed locally and on other servers.

It can be worked around by adding `"cacheDirectories": []` to `package.json`, but this disables caching and makes deployments slower.

It seems similar to [https://github.com/cloudfoundry/ibm-websphere-liberty-buildpack/issues/379](ibm-websphere-liberty-buildpack: Issue 379).

**Can you provide a sample app?**

No. The error seems to happen after a lot of deployments on a single server. It occurred on ours after ~130 deployments of a large app.

**Please confirm where necessary:**
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by SilverFox70** [comment]
Having the same problem with our app, except that adding "cacheDirectories": [] to package.json doesn't help.

**Comment by sclevine** [comment]
These apps are running out of disk space during staging. Can you provide the staging disk quota on the foundations where this is failing?

**Comment by jfeeny** [comment]
@AlexOwen We're going to go ahead and close this issue due to inactivity, but feel free to reopen it if you need more help with this issue.
