### ISSUE TITLE
Installation of node modules through a private npm repo

### ISSUE THREAD

**Issue by rahul-ranjan-me** [cloudfoundry/nodejs-buildpack#154]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
6.33.0+a345ea34d.2017-11-20

What version of the buildpack you are using?
1.6.21

If you were attempting to accomplish a task, what was it you were attempting to do?
I want to install node packages from a private npm repository

What did you expect to happen?
Hi, I am looking to install node modules through my private repos https://registry.npmjs.org. Can it be possible without customizing the buildpack?

What was the actual behavior?
It is installing node modules from https://registry.npmjs.org

I also have tried giving the registry information through .npmrc but it still going external registry

**Comment by astrieanna** [comment]
@rahul-ranjan-me From looking at the buildpack code, it doesn't appear that this buildpack would prevent you from using other registeries. What have you tried that works locally on your machine but not when pushing an app with the buildpack?

**Comment by rahul-ranjan-me** [comment]
Thanks for the reply. The issue was with the npm pack script which ignores .npmrc files while generating the bundled artefact.

**Comment by ketsthechanger** [comment]
@rahul-ranjan-me - can you please tell what was the fix here ? I'm facing the same issue that npm is trying to fetch packages from public registry rather than private npm registry

**Comment by rahul-ranjan-me** [comment]
@ketsthechanger you need to setup the following env variable through manifest.yml something like

applications:
- name: yourapplicationname
  routes:
    - route: yourapplicationroute
  env:
    npm_config_registry: path to your internal registry

**Comment by tarunmangla07** [comment]
@rahul-ranjan-me, is there any specific way to provide the path to internal registry as i am getting address not found error. could you elaborate more on this?

**Comment by rahul-ranjan-me** [comment]
> @rahul-ranjan-me, is there any specific way to provide the path to internal registry as i am getting address not found error. could you elaborate more on this?

you need to setup the following env variable through manifest.yml something like

applications:

name: yourapplicationname
routes:
route: yourapplicationroute
env:
npm_config_registry: path to your internal registry

**Comment by sw-ot-shanilshah** [comment]
Hello Team,

Does anyone know how to pass CI_JOB_TOKEN to npm_config_registry?
