### ISSUE TITLE
Support for disabling "production" flag when running `npm install`

### ISSUE THREAD

**Issue by svennam92** [cloudfoundry/nodejs-buildpack#16]
Opened a discussion here: https://groups.google.com/a/cloudfoundry.org/forum/#!topic/vcap-dev/QXbHOuNXAt8

Currently, when installing the dependencies for a user's Node app, we run this command:
  npm install --userconfig $build_dir/.npmrc --production 2>&1 | indent

Seems that it would be valuable to give users the option to disable the "--production" flag so that their "devDependencies" in package.json can be installed.  One use case is for developers who want their grunt dependencies installed on production, but it's a hassle because those dependencies are generally under "devDependencies".

Heroku's Node.js bulidpack supports this functionality via NPM_CONFIG_PRODUCTION

I'd be happy to open a PR should we decide to include this support!

**Comment by flavorjones** [comment]
Hi,

We'll look into this. It's possible that we can merge this in from upstream Heroku; or even that we incompletely merged the feature (I see NPM_CONFIG_PRODUCTION being set in our `lib/build.sh`, but I don't see it being used).

**Comment by svennam92** [comment]
Seems to be working now!
