### ISSUE TITLE
Disable the certificate verification while down;o

### ISSUE THREAD

**Issue by jitheshktv** [cloudfoundry/nodejs-buildpack#165]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
cf version 6.34.1+bbdf81482.2018-01-17

What version of the buildpack you are using?
1.6.30

If you were attempting to accomplish a task, what was it you were attempting to do?
build an offline buildpack using the node.js binary from an internal repo

What did you expect to happen?
The build should create a cached/offline buildpack successfully after downloading the required dependency and packaging it.

What was the actual behavior?
Failed to download the dependency and create the package, as the ssl validation failed.
2018/10/26 14:20:11 error while creating zipfile: Get https://www.artifactrepository.xxxxxx.net/artifactory/xxxxx/nodejs/node-v6.9.1-linux-x64.tar.gz: x509: certificate signed by unknown authority

Can you provide a sample app?
N/A. Looking for the steps to disable the ssl validation while downloading and packaging the dependency.

Please confirm where necessary:
* [* ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by jitheshktv** [comment]
The NodeJS binary is hosted on an internal repo and I am looking for the steps to disable the ssl validation while downloading and packaging the dependency in the buildpack.

Thanks,
JK

**Comment by sclevine** [comment]
This seems like a feature request for the buildpack packager, which lives here:
https://github.com/cloudfoundry/libbuildpack/tree/master/packager

It is currently not possible to disable SSL validation in the packager. As a workaround, you could install a CA certificate for your artifactory repo on your workstation.

**Comment by jitheshktv** [comment]
Thanks @sclevine 

Cheers,
JK

**Comment by jitheshktv** [comment]
@sclevine The download process by default looks for the certificate at “/etc/pki/tls/certs/ca-bundle.crt“. Is there a way we can configure the certificate path, to use a different certificate?

Thanks,
JK
