### ISSUE TITLE
Use custom certificate for SSL validation for package manager

### ISSUE THREAD

**Issue by jitheshktv** [cloudfoundry/nodejs-buildpack#170]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running cf curl /v2/info && cf version?
cf version 6.34.1+bbdf81482.2018-01-17

What version of the buildpack you are using?
1.6.30

If you were attempting to accomplish a task, what was it you were attempting to do?
build an offline buildpack using the node.js binary from an internal repo

What did you expect to happen?
The build should create a cached/offline buildpack successfully after downloading the required dependency and packaging it.

What was the actual behavior?
Failed to download the dependency and create the package, as the ssl validation failed.
2018/10/26 14:20:11 error while creating zipfile: Get https://www.artifactrepository.xxxxxx.net/artifactory/xxxxx/nodejs/node-v6.9.1-linux-x64.tar.gz: x509: certificate signed by unknown authority
* About to connect() to www.artifactrepository.citigroup.net port 443 (#0)
*   Trying 169.177.244.86... connected
* Connected to www.artifactrepository.citigroup.net (169.177.244.86) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* Certificate is signed by an untrusted issuer: 'CN=Citi Device CA1 G2,O=Citigroup Inc.,C=US'
* NSS error -8172
* Closing connection #0
* Peer certificate cannot be authenticated with known CA certificates

curl: (60) Peer certificate cannot be authenticated with known CA certificates
More details here: http://curl.haxx.se/docs/sslcerts.html

Can you provide a sample app?
N/A. Looking for the steps to disable the ssl validation while downloading and packaging the dependency.

Please confirm where necessary:

[* ] I have included a log output
  My log includes an error message
  I have included steps for reproduction

Understand from issue 165 that It is currently not possible to disable SSL validation in the packager, and as a workaround, we could install a CA certificate for the artifactory repo on my workstation. The download process by default looks for the certificate at “/etc/pki/tls/certs/ca-bundle.crt“. Is there a way we can configure the certificate path, to use a different certificate?

**Comment by jitheshktv** [comment]
@sclevine Could you please check and respond? Opened it as a new issue since #165 is closed

**Comment by tylerphelan** [comment]
@jitheshktv you should be able to add the trusted CA to whatever machine is doing the downloads to get this to work as this uses the Go stdlib `http` package. On Redhat you can update `/etc/pki/ca-trust/source/anchors` with the CA file and run `/bin/update-ca-trust`.

Feel free to re-open if you have more questions.
