### ISSUE TITLE
Usage in offline environment

### ISSUE THREAD

**Issue by zhongyi-zhang** [cloudfoundry/nodejs-buildpack#173]
>What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

@dawu415 can provide them. But I think they are not related in the issue. 

>What version of the buildpack you are using?

@dawu415 can provide it. But I think it is not related in the issue. 

>If you were attempting to accomplish a task, what was it you were attempting to do?

Push an app in offline environment.

>What did you expect to happen?

The app succeeds to start.

>What was the actual behavior?

Timeout at installing node packages.

Can you provide a sample app?

Please refer to the discussion https://github.com/Azure/meta-azure-service-broker/issues/198.
In short: the app followed the [guidance here](https://docs.cloudfoundry.org/buildpacks/node/index.html#vendoring), vendored `node_modules`, added `package-lock.json`. Then it still got stuck here: https://github.com/cloudfoundry/nodejs-buildpack/blob/master/src/nodejs/npm/npm.go#L49-L51. The `fsevents` is a transitive optional dependency. It supports Darwin OS only. So it is not vendored and can't be vendored. But it is in the `package-lock.json` while it is actually not installed by `npm install`. Then, `npm install` in buildpack still tries to install it by network calls. That made it stuck. That's my understanding.
Appreciate any of your help or ideas. Thanks a bunch!

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by dawu415** [comment]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running cf curl /v2/info && cf version?
```~/Downloads/meta-azure-service-broker-1.10.0$ cf curl /v2/info
{
   "name": "Pivotal Application Service",
   "build": "2.2.9-build.5",
   "support": "https://support.pivotal.io",
   "version": 0,
   "description": "https://docs.pivotal.io/pivotalcf/2-2/pcf-release-notes/runtime-rn.html",
   "authorization_endpoint": "https://login.sys.sgp.pcf.manulife.com",
   "token_endpoint": "https://uaa.sys.sgp.pcf.manulife.com",
   "min_cli_version": "6.23.0",
   "min_recommended_cli_version": "6.23.0",
   "api_version": "2.112.0",
   "app_ssh_endpoint": "ssh.sys.sgp.pcf.manulife.com:2222",
   "app_ssh_host_key_fingerprint": "ff:c6:1e:f3:d5:6c:67:cd:63:de:bb:68:7a:23:c1:61",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.sys.sgp.pcf.manulife.com:443",
   "routing_endpoint": "https://api.sys.sgp.pcf.manulife.com/routing",
   "user": "640088cc-35cb-4c6f-a0e3-3f6f7a81052c"
}

~/Downloads/meta-azure-service-broker-1.10.0$ cf version
cf version 6.37.0+a40009753.2018-05-25

```

What version of the buildpack you are using?
We are using 1.6.32
```
nodejs_buildpack         5          true      false    nodejs_buildpack-cached-cflinuxfs2-v1.6.32.zip
```

**Comment by dawu415** [comment]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running cf curl /v2/info && cf version?
```~/Downloads/meta-azure-service-broker-1.10.0$ cf curl /v2/info
{
   "name": "Pivotal Application Service",
   "build": "2.2.9-build.5",
   "support": "https://support.pivotal.io",
   "version": 0,
   "description": "https://docs.pivotal.io/pivotalcf/2-2/pcf-release-notes/runtime-rn.html",
   "authorization_endpoint": "https://login.sys.sgp.pcf.xxx.com",
   "token_endpoint": "https://uaa.sys.sgp.pcf.xxx.com",
   "min_cli_version": "6.23.0",
   "min_recommended_cli_version": "6.23.0",
   "api_version": "2.112.0",
   "app_ssh_endpoint": "ssh.sys.sgp.pcf.xxx.com:2222",
   "app_ssh_host_key_fingerprint": "ff:c6:1e:f3:d5:6c:67:cd:63:de:bb:68:7a:23:c1:61",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.sys.sgp.pcf.xxx.com:443",
   "routing_endpoint": "https://api.sys.sgp.pcf.xxxx.com/routing",
   "user": "640088cc-35cb-4c6f-a0e3-3f6f7a81052c"
}

~/Downloads/meta-azure-service-broker-1.10.0$ cf version
cf version 6.37.0+a40009753.2018-05-25

```

What version of the buildpack you are using?
We are using 1.6.32
```
nodejs_buildpack         5          true      false    nodejs_buildpack-cached-cflinuxfs2-v1.6.32.zip
```

**Comment by sclevine** [comment]
If `fsevents` is a development dependency, can you try putting `only=prod` in `.npmrc` in the app directory?

**Comment by zhongyi-zhang** [comment]
Hi @sclevine, `fsevents` is a transitive [optional dependency](https://github.com/paulmillr/chokidar/blob/master/package.json#L43), `npm install --production` would still try to install it and finally skip it. Running `npm install --production --no-optional` can directly skip it. But thanks for reminding me with `.npmrc`! @dawu415 could you have a try putting `optional=false` in `.npmrc` and pushing?

**Comment by dawu415** [comment]
Sure, how about also including `only=prod` as well? (so we get production + no optional)

**Comment by zhongyi-zhang** [comment]
Yeah I just though the same thing. I ever edited the comment above :).

**Comment by dawu415** [comment]
Hi @zhongyi-zhang I tried the `optional=false` and `only=prod` (even tried only="prod").  This did not work.   
However, I did try `offline=true` and this worked.  https://docs.npmjs.com/misc/config#offline

**Comment by zhongyi-zhang** [comment]
@dawu415 that's good news! Could you create a PR to MASB? I am closing the issue here.
