### ISSUE TITLE
heroku deploy errors

### ISSUE THREAD

**Issue by darego1990** [cloudfoundry/nodejs-buildpack#175]
Hi guys,

I am trying to deploy the following web app with heroku:

https://github.com/darego1990/web1

although I get the following build log error and I am not sure why:

-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  0.12.x
       engines.npm (package.json):   2.5.x
       
       Resolving node version 0.12.x...
       Downloading and installing node 0.12.18...
       Bootstrapping npm 2.5.x (replacing 2.15.11)...
       npm 2.5.x installed
       
-----> Building dependencies
       Installing node modules (package.json + package-lock)
       react@16.6.3 node_modules/react
       ├── object-assign@4.1.1
       ├── prop-types@15.6.2
       ├── scheduler@0.11.3
       └── loose-envify@1.4.0 (js-tokens@4.0.0)
       
       react-dom@16.6.3 node_modules/react-dom
       ├── object-assign@4.1.1
       ├── loose-envify@1.4.0 (js-tokens@4.0.0)
       ├── prop-types@15.6.2
       └── scheduler@0.11.3
       
       next@7.0.2 node_modules/next
       ├── babel-core@7.0.0-bridge.0
       ├── htmlescape@1.1.1
       ├── fresh@0.5.2
       ├── etag@1.8.1
       ├── case-sensitive-paths-webpack-plugin@2.1.2
       ├── http-status@1.0.1
       ├── hoist-non-react-statics@2.5.5
       ├── ansi-html@0.0.7
       ├── path-to-regexp@2.1.0
       ├── nanoid@1.2.1
       ├── unfetch@3.0.0
       ├── babel-plugin-transform-react-remove-prop-types@0.4.15
       ├── strip-ansi@3.0.1 (ansi-regex@2.1.1)
       ├── babel-plugin-react-require@3.0.0
       ├── minimist@1.2.0
       ├── @babel/plugin-syntax-dynamic-import@7.0.0 (@babel/helper-plugin-utils@7.0.0)
       ├── @babel/plugin-proposal-object-rest-spread@7.0.0 (@babel/plugin-syntax-object-rest-spread@7.2.0, @babel/helper-plugin-utils@7.0.0)
       ├── http-errors@1.6.2 (setprototypeof@1.0.3, inherits@2.0.3, statuses@1.5.0, depd@1.1.1)
       ├── loader-utils@1.1.0 (emojis-list@2.1.0, big.js@3.2.0, json5@0.5.1)
       ├── webpack-hot-middleware@2.22.3 (html-entities@1.2.1, querystring@0.2.0)
       ├── prop-types@15.6.2 (object-assign@4.1.1, loose-envify@1.4.0)
       ├── send@0.16.1 (escape-html@1.0.3, destroy@1.0.4, ms@2.0.0, range-parser@1.2.0, encodeurl@1.0.2, statuses@1.3.1, depd@1.1.2, mime@1.4.1, on-finished@2.3.0, debug@2.6.9)
       ├── cross-spawn@5.1.0 (shebang-command@1.2.0, lru-cache@4.1.5, which@1.3.1)
       ├── del@3.0.0 (is-path-cwd@1.0.0, p-map@1.2.0, pify@3.0.0, rimraf@2.6.2, is-path-in-cwd@1.0.1, globby@6.1.0)
       ├── url@0.11.0 (punycode@1.3.2, querystring@0.2.0)
       ├── event-source-polyfill@0.0.12
       ├── mkdirp-then@1.2.0 (any-promise@1.3.0, mkdirp@0.5.1)
       ├── find-up@2.1.0 (locate-path@2.0.0)
       ├── glob@7.1.2 (path-is-absolute@1.0.1, inherits@2.0.3, fs.realpath@1.0.0, inflight@1.0.6, once@1.4.0, minimatch@3.0.4)
       ├── friendly-errors-webpack-plugin@1.7.0 (chalk@1.1.3, string-width@2.1.1, error-stack-parser@2.0.2)
       ├── react-error-overlay@4.0.0
       ├── prop-types-exact@1.2.0 (reflect.ownkeys@0.2.0, has@1.0.3, object.assign@4.1.0)
       ├── launch-editor@2.2.1 (shell-quote@1.6.1, chalk@2.4.1)
       ├── resolve@1.5.0 (path-parse@1.0.6)
       ├── recursive-copy@2.0.6 (slash@1.0.0, junk@1.0.3, pify@2.3.0, emitter-mixin@0.0.3, graceful-fs@4.1.15, errno@0.1.7, del@2.2.2, mkdirp@0.5.1, maximatch@0.1.0, promise@7.3.1)
       ├── webpack-dev-middleware@3.4.0 (range-parser@1.2.0, mime@2.4.0, webpack-log@2.0.0, memory-fs@0.4.1)
       ├── @babel/runtime@7.0.0 (regenerator-runtime@0.12.1)
       ├── source-map@0.5.7
       ├── webpack-sources@1.2.0 (source-list-map@2.0.1, source-map@0.6.1)
       ├── babel-loader@8.0.2 (find-cache-dir@1.0.0, mkdirp@0.5.1, util.promisify@1.0.0)
       ├── terser-webpack-plugin@1.0.2 (serialize-javascript@1.5.0, worker-farm@1.6.0, find-cache-dir@2.0.0, source-map@0.6.1, cacache@11.3.1, terser@3.11.0, schema-utils@1.0.0)
       ├── webpack@4.20.2 (json-parse-better-errors@1.0.2, loader-runner@2.3.1, schema-utils@0.4.7, @webassemblyjs/helper-module-context@1.7.8, acorn-dynamic-import@3.0.0, ajv-keywords@3.2.0, mkdirp@0.5.1, eslint-scope@4.0.0, chrome-trace-event@1.0.0, enhanced-resolve@4.1.0, memory-fs@0.4.1, tapable@1.1.1, @webassemblyjs/wasm-parser@1.7.8, @webassemblyjs/wasm-edit@1.7.8, acorn@5.7.3, neo-async@2.6.0, @webassemblyjs/ast@1.7.8, micromatch@3.1.10, webpack-sources@1.3.0, uglifyjs-webpack-plugin@1.3.0, watchpack@1.6.0, node-libs-browser@2.1.0, ajv@6.6.1)
       ├── webpackbar@2.6.3 (pretty-time@1.1.0, figures@2.0.0, consola@1.4.5, std-env@1.3.1, chalk@2.4.1, log-update@2.3.0, table@4.0.3, schema-utils@1.0.0, lodash@4.17.11)
       ├── @babel/core@7.0.0 (json5@0.5.1, semver@5.6.0, convert-source-map@1.6.0, @babel/helpers@7.2.0, debug@3.2.6, @babel/generator@7.2.0, @babel/code-frame@7.0.0, @babel/parser@7.2.0, @babel/traverse@7.1.6, @babel/types@7.2.0, lodash@4.17.11)
       ├── autodll-webpack-plugin@0.4.2 (find-cache-dir@1.0.0, make-dir@1.3.0, webpack-merge@4.1.5, memory-fs@0.4.1, tapable@1.1.1, read-pkg@2.0.0, bluebird@3.5.3, lodash@4.17.11)
       ├── write-file-webpack-plugin@4.3.2 (filesize@3.6.1, debug@3.2.6, mkdirp@0.5.1, chalk@2.4.1, moment@2.22.2, lodash@4.17.11)
       ├── @babel/template@7.0.0 (@babel/code-frame@7.0.0, @babel/parser@7.2.0, @babel/types@7.2.0)
       ├── @babel/plugin-transform-runtime@7.0.0 (@babel/helper-plugin-utils@7.0.0, resolve@1.8.1, @babel/helper-module-imports@7.0.0)
       ├── @babel/plugin-proposal-class-properties@7.0.0 (@babel/plugin-syntax-class-properties@7.2.0, @babel/helper-plugin-utils@7.0.0, @babel/helper-member-expression-to-functions@7.0.0, @babel/helper-optimise-call-expression@7.0.0, @babel/helper-function-name@7.1.0, @babel/helper-replace-supers@7.1.0)
       ├── @babel/preset-react@7.0.0 (@babel/plugin-transform-react-display-name@7.2.0, @babel/helper-plugin-utils@7.0.0, @babel/plugin-transform-react-jsx-source@7.2.0, @babel/plugin-transform-react-jsx-self@7.2.0, @babel/plugin-transform-react-jsx@7.2.0)
       ├── @babel/preset-env@7.0.0 (js-levenshtein@1.1.4, @babel/plugin-syntax-object-rest-spread@7.2.0, @babel/plugin-transform-arrow-functions@7.2.0, @babel/plugin-syntax-async-generators@7.2.0, @babel/plugin-transform-literals@7.2.0, @babel/plugin-syntax-optional-catch-binding@7.2.0, @babel/plugin-transform-shorthand-properties@7.2.0, @babel/plugin-proposal-optional-catch-binding@7.2.0, @babel/plugin-transform-block-scoped-functions@7.2.0, @babel/plugin-transform-duplicate-keys@7.2.0, @babel/plugin-transform-typeof-symbol@7.2.0, @babel/plugin-transform-new-target@7.0.0, @babel/plugin-transform-spread@7.2.0, @babel/plugin-transform-computed-properties@7.2.0, @babel/plugin-transform-for-of@7.2.0, @babel/helper-plugin-utils@7.0.0, @babel/plugin-transform-destructuring@7.2.0, semver@5.6.0, @babel/plugin-proposal-json-strings@7.2.0, invariant@2.2.4, @babel/plugin-transform-regenerator@7.0.0, browserslist@4.3.5, @babel/plugin-transform-block-scoping@7.2.0, @babel/plugin-transform-sticky-regex@7.2.0, @babel/plugin-transform-unicode-regex@7.2.0, @babel/plugin-transform-dotall-regex@7.2.0, @babel/plugin-transform-modules-amd@7.2.0, @babel/plugin-transform-modules-umd@7.2.0, @babel/plugin-proposal-unicode-property-regex@7.2.0, @babel/helper-module-imports@7.0.0, @babel/plugin-transform-function-name@7.2.0, @babel/plugin-transform-object-super@7.2.0, @babel/plugin-transform-template-literals@7.2.0, @babel/plugin-transform-modules-commonjs@7.2.0, @babel/plugin-transform-modules-systemjs@7.2.0, @babel/plugin-transform-parameters@7.2.0, @babel/plugin-proposal-async-generator-functions@7.2.0, @babel/plugin-transform-async-to-generator@7.2.0, @babel/plugin-transform-exponentiation-operator@7.2.0, @babel/plugin-transform-classes@7.2.0)
       ├── @babel/runtime-corejs2@7.0.0 (regenerator-runtime@0.12.1, core-js@2.6.0)
       └── styled-jsx@3.1.0 (stylis-rule-sheet@0.0.10, babel-plugin-syntax-jsx@6.18.0, string-hash@1.1.3, convert-source-map@1.5.1, stylis@3.5.3, source-map@0.7.3, babel-types@6.26.0)
       Running heroku-postbuild
       
       > my-app@1.0.0 heroku-postbuild /tmp/build_f85d5b0987590f76e56a2945b6c4ccc1
       > npm run build
       
       
       > my-app@1.0.0 build /tmp/build_f85d5b0987590f76e56a2945b6c4ccc1
       > next build
       
/tmp/build_f85d5b0987590f76e56a2945b6c4ccc1/node_modules/next/dist/bin/next:44
var inspectArg = process.argv.find(function (arg) {
                              ^
TypeError: undefined is not a function
    at Object.<anonymous> (/tmp/build_f85d5b0987590f76e56a2945b6c4ccc1/node_modules/next/dist/bin/next:44:31)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Linux 4.4.0-1031-aws
npm ERR! argv "node" "/tmp/build_f85d5b0987590f76e56a2945b6c4ccc1/.heroku/node/bin/npm" "run" "build"
npm ERR! node v0.12.18
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! my-app@1.0.0 build: `next build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-app@1.0.0 build script 'next build'.
npm ERR! This is most likely a problem with the my-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     next build
npm ERR! You can get their info via:
npm ERR!     npm owner ls my-app
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/build_f85d5b0987590f76e56a2945b6c4ccc1/npm-debug.log
npm ERR! Linux 4.4.0-1031-aws
npm ERR! argv "node" "/tmp/build_f85d5b0987590f76e56a2945b6c4ccc1/.heroku/node/bin/npm" "run" "heroku-postbuild" "--if-present"
npm ERR! node v0.12.18
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! my-app@1.0.0 heroku-postbuild: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-app@1.0.0 heroku-postbuild script 'npm run build'.
npm ERR! This is most likely a problem with the my-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls my-app
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/build_f85d5b0987590f76e56a2945b6c4ccc1/npm-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

**Comment by kardolus** [comment]
We don't support the heroku buildpacks. This is the cloud foundry nodejs-buildpack repository.
