### ISSUE TITLE
Versions >1.6.34 not supporting huge JWT Tokens

### ISSUE THREAD

**Issue by manishaskani** [cloudfoundry/nodejs-buildpack#178]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
Nodejs Buildpack version 1.6.42
stack: cflinuxfs2

What version of the buildpack you are using?
1.6.42

If you were attempting to accomplish a task, what was it you were attempting to do?
I am sending a web request with Authentication as 'Bearer XXXX'. This token length pretty huge about 10000 characters length. This is not a problem if I use #v1.6.34 but once we upgrade to latest buildpack versions, we are getting either 502 Gateway Timeout or 400 Bad Request errors directly without even processing single line of code. I suppose this is because it is not able to take the huge token inside req.authinfo parameter which I use from passport js. 

What did you expect to happen?
Expected to work fine in newer buildpack versions.

What was the actual behavior?
It fails with 502 or 400 errors for bigger jwt tokens.

Can you provide a sample app?

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by sclevine** [comment]
This is the same issue as #176. The change was due to an upstream patch to a high CVE. It can be manually reverted back with CLI parameters (see #176), but that may be dangerous.

**Comment by manishaskani** [comment]
Thanks for pointing to the duplicate issue. It worked for me as well. :)
