### ISSUE TITLE
Node js version 8.11.4 not supported.

### ISSUE THREAD

**Issue by aniltomar10** [cloudfoundry/nodejs-buildpack#181]
I am using cloud foundry CLI for node js application deployment. In my application's package.json I have specified node js version "8.11.4".  Application deployment is failing now because cloud foundry is using latest version of nodejs_buildpack which doesn't support node js version 8.11.4

If I remove node js version setting from my package json file then nodejs_buildpack by default is using old version of node js. Because of that my application is not working.

One option I have is to modify my package json file and use latest version of node js which is supported by nodejs_buildpack, but this is not permanent fix because in future I may end up in same situation.

What should I do. Please suggest.

**Comment by Zanadar** [comment]
@aniltomar10 Best way is to specify your node version using a semver range eg `engines.node: 6.x` see: https://docs.cloudfoundry.org/buildpacks/node/index.html#runtime
