### ISSUE TITLE
Notice: Removal of Node.js 6.x in Node.js buildpack after April 11, 2019

### ISSUE THREAD

**Issue by shanks3012** [cloudfoundry/nodejs-buildpack#183]
The first release of the Node.js buildpack after April 11, 2019 will no longer include any versions of Node.js 6.x. These Node.js versions are no longer supported upstream [1]. Please migrate your Node.js apps to supported versions of Node.js before that time. 

Note: The default version of Node.js in the buildpack will be changed from Node.js 6.x to Node.js 10.x at this time.

[1] https://github.com/nodejs/Release

**Comment by kardolus** [comment]
Fixed in this commit: https://github.com/cloudfoundry/nodejs-buildpack/commit/6cf46a18b1b9e9af816f965d5b7a446c43d5c180
