### ISSUE TITLE
Notice: Default Node.js version will change from 6.x to 10.x after April 11, 2019

### ISSUE THREAD

**Issue by shanks3012** [cloudfoundry/nodejs-buildpack#184]
The default version of Node.js in the Node.js buildpack will change from the latest 6.x version to the latest 10.x version in the first release of the Node.js buildpack after April 11, 2019. Due to the end of upstream support for Node.js 6.x in April, all buildpack users should ensure that their apps run on a minimum buildpack supported version of Node.js 10.x or later.

For more information about Node.js 10.x or LTS timelines for 10.x, refer to: https://github.com/nodejs/Release

For more information about supported Node.js versions in the node.js buildpack, refer to: https://buildpacks.cloudfoundry.org/#/buildpacks

**Comment by ndon55555** [comment]
https://github.com/cloudfoundry/nodejs-buildpack/commit/f0ceb3179301964bfea52819ee2715c7f3000f2e
