### ISSUE TITLE
cflinuxfs2 is deprecated

### ISSUE THREAD

**Issue by ramzes13** [cloudfoundry/nodejs-buildpack#185]
Hello, 
I have this warning on deploy:

```
-----> Nodejs Buildpack version 1.6.45
       **WARNING** 
       ⚠️️️ 🚨️️ ⚠️ 🚨️️
       This application is being deployed on cflinuxfs2 which is being deprecated in April, 2019.
       Please migrate this application to cflinuxfs3.
```

There are some migration plans on `cflinuxfs3` ?

**Comment by sclevine** [comment]
Hi @ramzes13,

See [here](http://cf-dev.70369.x6.nabble.com/cf-dev-cflinuxfs2-gt-cflinuxfs3-transition-td8959.html) and [here](https://docs.cloudfoundry.org/devguide/deploy-apps/stacks.html). We currently publish versions of the buildpack for both stacks.

Additionally, if you're using a commercial distribution of CF, your vendor may have guidelines specific to your platform.

**Comment by ramzes13** [comment]
Hi @sclevine , thanks for the answer.
At the moment we use a [manifest.yml](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html) file to deploy nodejs app.

```
path: .
name: app-name
buildpack: https://github.com/cloudfoundry/nodejs-buildpack
services:
...
```
I searched on [Node.js Buildpack](https://docs.cloudfoundry.org/buildpacks/node/index.html) how to use cflinuxfs3.
I did not find any way to configure it.
It is possible to do that?

**Comment by ramzes13** [comment]
I used this manifest config: 
```
path: .
stack: cflinuxfs3
name: app-name
buildpack: https://github.com/cloudfoundry/nodejs-buildpack
services:
...
```
And I have this output:
```
Using manifest file manifest_test.yml
Using manifest file manifest_test.yml

Using stack cflinuxfs3...
FAILED
Stack cflinuxfs3 not found
```

For `cf stacks` :
```
OK

name         description
lucid64      Ubuntu 10.04 on x86-64
cflinuxfs2   Ubuntu 14.04.2 trusty
```

**Comment by sclevine** [comment]
Your foundation operator needs to install cflinuxfs3 for buildpacks to use it.

**Comment by ramzes13** [comment]
Ok Thx
