### ISSUE TITLE
IMPORTANT NOTICE: End of support for nodejs versions 11.x after 2019-06-05

### ISSUE THREAD

**Issue by shanks3012** [cloudfoundry/nodejs-buildpack#195]
The first release of the Node.js buildpack after June 05, 2019 will no longer include any versions of Node.js 11.x. These Node.js versions are no longer supported upstream [1]. Please migrate your Node.js apps to supported versions of Node.js before that time. 

Note: Unless you are manually specifying a version of Node.js for the buildpack to use, or you have customized your Node.js buildpack, no action is required.

[1] https://github.com/nodejs/Release

**Comment by sclevine** [comment]
@eshanks reminder about this issue
