### ISSUE TITLE
Nodejs_buildpack, how to set npm proxy repository

### ISSUE THREAD

**Issue by adharbert** [cloudfoundry/nodejs-buildpack#197]
**- What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?**
C:\>cf -v
   cf version 6.32.0+0191c33d9.2017-09-26
   "api_version": "2.98.0",

**-What version of the buildpack you are using?**
 nodejs_buildpack 1.6.28

**- If you were attempting to accomplish a task, what was it you were attempting to do?**
I am trying to deploy a node / react application and ignore the node_modules folders.  With all the node packs included, my cf push takes almost 40 minutes.  My main issue is my company has it's own npm repository so need to point to that proxy

**What did you expect to happen?**
I was hoping to deploy the application and npm install would occur and the application push would be much faster.

**What was the actual behavior?**
When the build pack get to the part of "Building dependencies / Installing node modules (package.json + package-lock.json)"  I would get an error ENOTFOUND, the network request is trying to find npm server instead of our company server.

I even tried to add the proxy and https-proxy to the manifest.yml file, but it ignores that.

Any idea how we can get the build process to see our internal proxy, that would be great.

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by Zanadar** [comment]
@adharbert You should be able to include an `.npmrc` file in the root of your app and set the registry option (https://docs.npmjs.com/misc/config#registry) to point to your internal registry.
Re-open if you continue to have issues.
