### ISSUE TITLE
Running `npm prune` even when "node_modules" is checked in

### ISSUE THREAD

**Issue by svennam92** [cloudfoundry/nodejs-buildpack#20]
The default behavior for restoring cache and "pruning" is not consistent with Heroku or legacy behavior.  When a user checks in `node_modules`, the buildpack will still run `npm prune` as part of `restore_npm_cache`.

If I want to push some dependencies in `node_modules` with my application (even though it's an anti-pattern), the buildpack will wipe them out if I don't have them explicitly listed in my `package.json`.  This is not how it worked before.

We should really only run `npm prune` if there is a `npm-shrinkwrap.json` or `package.json` AND no `node_modules` in the application.  The behavior in the past was that if `node_modules` is checked in, we completely skip the caching process because we cannot ensure that a user has explicitly declared those dependencies in their package.json/shrinkwrap.

See here:
https://github.com/cloudfoundry/nodejs-buildpack/blob/master/lib/build.sh#L162
and
https://github.com/heroku/heroku-buildpack-nodejs/blob/master/lib/build.sh#L186

EDIT: I opened PR #21 to address this issue and Issue #22

**Comment by jtarchie** [comment]
@svennam92, thanks for the feedback. After some investigation, it looks like the Heroku buildpack has updated since we pulled from upstream.

At one point they had this [functionality](https://github.com/cloudfoundry/nodejs-buildpack/commit/cc9339a1bb0143a3742bce4bc5cae3299e6cae94).

@flavorjones and I will put a story in out backlog to pull down the most recent changes.

Thanks!

**Comment by svennam92** [comment]
Awesome, thanks!  There are also some other important changes in that same space that need to be pulled in

You used to have it:
https://github.com/cloudfoundry/nodejs-buildpack/blob/cc9339a1bb0143a3742bce4bc5cae3299e6cae94/lib/build.sh#L174
but not any longer:
https://github.com/cloudfoundry/nodejs-buildpack/commit/f43aa9681932f78025796dcc8e913b639c3635b2#diff-cbea48db73996bd0b8adcff9b6b7fbd2L186

I assume this will also get merged in from upstream -- we need to install any new dependencies after doing the "rebuild". This allows some dependencies to be pushed with the application in "node_modules", and others to be downloaded as specified in `package.json`

**Comment by flavorjones** [comment]
Should be addressed when we merge upstream in https://www.pivotaltracker.com/story/show/93482010

We'll leave this open until we merge and verify we've addressed it.

**Comment by flavorjones** [comment]
This is fixed in `nodejs-buildpack` v1.3.3:

* https://github.com/cloudfoundry/nodejs-buildpack/releases/tag/v1.3.3

We've also submitted a PR to runtime to have this version bundled with `cf-release:

* https://github.com/cloudfoundry/cf-release/pull/685

Thanks again for reporting this!
