### ISSUE TITLE
App name displayed in New Relic has the appId appended

### ISSUE THREAD

**Issue by febinrejoe** [cloudfoundry/nodejs-buildpack#201]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

6.44.0+5de0f0d02.2019-05-01

What version of the buildpack you are using?

nodejs_buildpack-cached-cflinuxfs3-v1.6.51.zip

If you were attempting to accomplish a task, what was it you were attempting to do?

Configure New Relic for a nodejs app

What did you expect to happen?

The App name shown in New Relic to be the same as the App name displayed in CF

What was the actual behavior?

The App name shown in New Relic has the `application_id` appended to it. For e.g. if the app name in cf is `my-app-staging`, the app name shown in New Relic is displayed as `my-app-staging-3d277ba3-cd5c-48e9-a466-0eb5e0909039`.

This is because of https://github.com/cloudfoundry/nodejs-buildpack/blob/master/profile/newrelic-setup.sh#L16

Any reason why the `VCAP_APPLICATION.application_id` is appended to the `VCAP_APPLICATION.application_name`?

**Comment by febinrejoe** [comment]
Also I know I can set the App name by overriding `NEW_RELIC_APP_NAME` (environment variable), but curious to know if appending the appId to the app name adds any value. If not, we can probably remove it.

**Comment by dfreilich** [comment]
@sclevine Any thoughts on this?

**Comment by dfreilich** [comment]
@febinrejoe I'm not sure, but I would assume that this is because you may be pushing multiple versions of an app, and we'd want the app name to accurately reflect the uid of the app. I'll close this for now.

**Comment by febinrejoe** [comment]
@dfreilich even if it is to capture different version of the App, appending the application id does not really make sense as its not going to tell me what exact version I am running. Also the behavior is different from the Java buildpack
