### ISSUE TITLE
Missing latest Node versions

### ISSUE THREAD

**Issue by web-bert** [cloudfoundry/nodejs-buildpack#205]
Not sure if this is the correct place to ask, but just wondering if you are planning to add support for Node.js versions 10.6.1, 10.6.2 and 10.6.3

Thanks

**Comment by sclevine** [comment]
Already on the develop branch: https://github.com/cloudfoundry/nodejs-buildpack/blob/develop/manifest.yml

We should have a release out today or early next week. Apologies for the delay!

**Comment by web-bert** [comment]
Great, thanks @sclevine

**Comment by dwillist** [comment]
We are about to cut this release today, changes are already on master. Just too clarify, we have added node 10.16.0 and 10.16.3, but have no plans to add anything from the previous minor line 10.6.x.

**Comment by web-bert** [comment]
Great thanks @dwillist 10.16.3 is what I was after

**Comment by web-bert** [comment]
The tag/release has not been made yet, any idea when it will be available?
