### ISSUE TITLE
using https.createServer in production

### ISSUE THREAD

**Issue by dagda1** [cloudfoundry/nodejs-buildpack#206]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

What version of the buildpack you are using?

1.6.50

If you were attempting to accomplish a task, what was it you were attempting to do?

At the moment I am creating an http server in the production environment:

```javascript
const server = http.createServer(app);

let currentApp = app;

server.listen(process.env.PORT, (error: Error) => {
  if (error) {
    console.log(error);
  }

  console.log(`started on ${process.env.PORT}`);
});
```
As it is production should I be doing something like this:

```
var options = {
  key: fs.readFileSync(path.join('certs', 'my-server.key.pem')),
  cert: fs.readFileSync(path.join('certs', 'my-server.crt.pem'))
};

var server = https.createServer(options);
```
How would I be able to find the paths to the key and cert files?

I know there is a `CF_SYSTEM_CERT_PATH` and if I do an `ls` in that dir, I can see 3 certificates.  

Which one should I use and where would I get the key files?

I'm not sure which one I should be using

**Comment by sclevine** [comment]
Apologies for the delayed response. Assuming you're running on Cloud Foundry, TLS termination is handled at the gorouter or load balancer level, and not by application code. See: https://docs.cloudfoundry.org/adminguide/securing-traffic.html
