### ISSUE TITLE
Node 12.10.0 fails

### ISSUE THREAD

**Issue by ClayShentrup** [cloudfoundry/nodejs-buildpack#208]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

cf version 6.46.1+4934877ec.2019-08-23

What version of the buildpack you are using?

**WARNING** buildpack version changed from 1.6.30 to 1.6.56

If you were attempting to accomplish a task, what was it you were attempting to do?

Just get the build step working with `cf local`

What did you expect to happen?

Node 12.10.0 would be available.

What was the actual behavior?

`**ERROR** Unable to install node: no match found for 12.10.0 in [8.16.0 8.16.1 10.14.2 10.15.0]`

Can you provide a sample app?

No. Reproduce steps:
```
cf local stage notebooks-frontend -p app/notebooks/ && cf local run notebooks-frontend
```

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by dwillist** [comment]
@ClayShentrup Hey thanks for opening an issue. It would appear that you are using `cflinuxfs2` which does not support using `node 12`. It also seems like this question has been resolved [here](https://cloudfoundry.slack.com/archives/C02HWMDUQ/p1568906590030700). Please feel free to reopen.
