### ISSUE TITLE
IMPORTANT NOTICE: End of support for Node.js versions 8.x after 2020-01-05

### ISSUE THREAD

**Issue by shanks3012** [cloudfoundry/nodejs-buildpack#216]
The first release of the Node.js buildpack after January 5, 2020 will no longer include Node.js versions 8.x. These Node.js versions will no longer be supported upstream.[1] Please migrate your Node.js apps to supported versions of Node.js before that time.

Note: While the default version of Node.js in the Node.js buildpack is 10.x, it is recommended that you ensure your Node.js applications are not specifying a Node.js version of 8.x in either a buildpack.yml, .nvmrc, or package.json files. As always, the buildpacks team is happy to answer questions you may have about this deprecation in the #buildpacks Slack channel.

[1] https://nodejs.org/en/about/releases/

**Comment by ryanmoran** [comment]
@kvedurmu can this be closed out?

**Comment by kvedurmu** [comment]
oops. thanks! We forget to close these out sometimes when deprecating dependencies..
