### ISSUE TITLE
New buildpack required to support latest security releases

### ISSUE THREAD

**Issue by web-bert** [cloudfoundry/nodejs-buildpack#217]
I appreciate these have only just been released, but I wanted to bring it to your attention, there are [new security releases](https://nodejs.org/en/blog/vulnerability/february-2020-security-releases/) so we need a new buildpack to ensure we can update to the latest:

- Node.js v10.19.0 (LTS)
- Node.js v12.15.0 (LTS)
- Node.js v13.8.0 (LTS)

These releases cover One Critical severity and two High severity issues

Thank you

**Comment by ryanmoran** [comment]
@web-bert this was released yesterday as [v1.7.11](https://github.com/cloudfoundry/nodejs-buildpack/releases/tag/v1.7.11). Thanks!
