### ISSUE TITLE
Install any new modules after "rebuilding" existing dependencies

### ISSUE THREAD

**Issue by svennam92** [cloudfoundry/nodejs-buildpack#22]
Seems we are missing some important logic to install any new modules when rebuilding existing dependencies

You used to have it:
https://github.com/cloudfoundry/nodejs-buildpack/blob/cc9339a1bb0143a3742bce4bc5cae3299e6cae94/lib/build.sh#L174
but not any longer:
https://github.com/cloudfoundry/nodejs-buildpack/commit/f43aa9681932f78025796dcc8e913b639c3635b2#diff-cbea48db73996bd0b8adcff9b6b7fbd2L186

We should install any new dependencies after doing the "rebuild". This allows some dependencies to be pushed with the application in "node_modules", and others to be downloaded as specified in package.json

My scenario that caused this issue:
Push fresh application (no cache) with undeclared dependencies in `node_modules`. This is considered `prebuilt`, so it rebuilds the dependencies I've included in `node_modules`. However, I had `express` in my `package.json` (but not in `node_modules`), and it never got installed.

**Comment by flavorjones** [comment]
Should be addressed when we merge upstream in https://www.pivotaltracker.com/story/show/93482010

We'll leave this open until we merge and verify we've addressed it.

**Comment by flavorjones** [comment]
This is fixed in `nodejs-buildpack` v1.3.3:

* https://github.com/cloudfoundry/nodejs-buildpack/releases/tag/v1.3.3

We've also submitted a PR to runtime to have this version bundled with `cf-release:

* https://github.com/cloudfoundry/cf-release/pull/685

Thanks again for reporting this!
