### ISSUE TITLE
Node application installing devDependencies even when NODE_ENV=production

### ISSUE THREAD

**Issue by rpower86** [cloudfoundry/nodejs-buildpack#220]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
CF_CLI: "6.23.0"
cf version: 6.46.1+4934877ec.2019-08-23

What version of the buildpack you are using?
nodejs v1.6.45

If you were attempting to accomplish a task, what was it you were attempting to do?
I was trying to deploy a production nodejs application to our PCF environment.

What did you expect to happen?
During staging of the application, dependencies would be downloaded correct ignoring the devDependancies

What was the actual behavior?
During staging of the application both the Dependencies and development dependencies were installed. 

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [x ] I have included steps for reproduction

In the logs I can see NODE_ENV=production is being set and cf ssh'ing in the application I can see that the application has the var NODE_ENV set to production. However when deploying the application using cf push it still attempts to install the dev dependencies.

**Comment by ForestEckhardt** [comment]
@rpower86 this is a problem that was discovered and has been resolved in our cf-compatible-cnb builds of this buildpack which you can find [here](https://github.com/cloudfoundry/nodejs-cnb/releases). We are limiting the changes that we make to nodejs buildpack to dependency updates and major bug fixes and instead focusing on building out the new Cloud Native Buildpacks ecosystem under the [Paketo](https://github.com/paketo-buildpacks) project. If you find that you still are having a problem with the cf-compatible-cnb then please open an issue on the [npm](https://github.com/paketo-buildpacks/npm) repo in the Paketo project. Thanks!
