### ISSUE TITLE
Unnecessary warning for .nvmrc and package.json engine definition

### ISSUE THREAD

**Issue by hendriku** [cloudfoundry/nodejs-buildpack#221]
**What version of the buildpack you are using?**

Based on Cloud Foundry Node.js Buildpack 1.7.17

**If you were attempting to accomplish a task, what was it you were attempting to do?**

Pushing an app to the cloud.

**What did you expect to happen?**

I did not expect to get the warning
`          **WARNING** Node version in .nvmrc ignored in favor of 'engines' field in package.json
`
because these versions are the same

**What was the actual behavior?**

In my opinion it is best practise to have no inconsistency between those to version definitions. They should always be the same. Therefore a warning that one of the definitions is being ignored is not useful. 

It would be better to check if the versions in .nvmrc and package.json engine field do mismatch and IF YES, then print a warning that one of it is being ignored.

**Can you provide a sample app?**

Just define package.json engines field together within .nvmrc in any app.

**Please confirm where necessary:**
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by ryanmoran** [comment]
This should be resolved in https://github.com/cloudfoundry/nodejs-buildpack/commit/478f9d55da30a55848136e536058907396e48bde and will come out in the next release.
