### ISSUE TITLE
Need the latest fix of libbuildpack-dynatrace module in the nodejs buildpack

### ISSUE THREAD

**Issue by manitheja1** [cloudfoundry/nodejs-buildpack#242]
Hi Team,
I could see the libbuildpack dynatrace module in the nodejs buildpack is using 1.2.2 version. There has been a latest release(1.3.0) for the module which has a fix to customize oneagenturl(https://github.com/Dynatrace/libbuildpack-dynatrace/releases ). 

We need that fix in the nodejs buildpack. I know. could you please help us in getting the new release which will have the latest release of libbuildpack-dynatrace?

Thanks,
Manitheja

**Comment by ForestEckhardt** [comment]
@manitheja1 The module has been updated in this commit https://github.com/cloudfoundry/nodejs-buildpack/commit/50ef1a326dff3e4e04729f3240cdc5c9aaf4aa5c. This will make it out in the next release of the buildpack.

**Comment by manitheja1** [comment]
Hi @ForestEckhardt ,
Thanks for the information!! May i know when will be the next release date/week approximately?
It would be great help for us so that we can plan accordingly for the release!!
Thanks,
Manitheja

**Comment by kvedurmu** [comment]
This has been released in the latest version of the buildpack - https://github.com/cloudfoundry/nodejs-buildpack/releases/tag/v1.7.29
