### ISSUE TITLE
How to create a node.js buildpack which has `Intl` (ECMA-402) support, and push it to Bluemix

### ISSUE THREAD

**Issue by liujul** [cloudfoundry/nodejs-buildpack#27]
Node.js does not support ECMA-402 by default.  Now I want to rebuild a node.js binary to include ECMA-402 support with ./configure --with-intl=full-icu --download=all. How can I have this buildpack to push the customized node.js to Bluemix as a buildpack? 

I checked file nodejs-buildpack-master\lib\binaries.sh, I saw the following instructions:
echo "Downloading and installing node $version..."
  local download_url="http://s3pository.heroku.com/node/v$version/node-v$version-$os-$cpu.tar.gz"
  (curl `translate_dependency_url $download_url` -s --fail -o - | tar xzf - -C /tmp)  || (echo -e "\n-----> Resource $download_url does not exist." 1>&2 ; exit 22)
  mv /tmp/node-v$version-$os-$cpu/* $dir
  chmod +x $dir/bin/*
Can I overwrite the instructions to the node.js with ECMA-402 support? 

---------------------------------------------------------------------------
### `Intl` (ECMA-402) support:
[Intl](https://github.com/joyent/node/wiki/Intl) support is not
enabled by default.

#### Build with full ICU support (all locales supported by ICU):
With the `--download=all`, this may download ICU if you don't
have an ICU in `deps/icu`.

Unix/Macintosh:
```sh
./configure --with-intl=full-icu --download=all
```

**Comment by jtarchie** [comment]
@liujul, we currently build our binaries with [binary builder](https://github.com/cloudfoundry/binary-builder) project. Looking over the dependencies for `Intl`, we might not have all the packages installed on the [stack](https://docs.cloudfoundry.org/concepts/stacks.html).

If you do manage to compile your own binary, you'll need to package it up with your own fork of the nodejs buildpack. You can edit `manifest.yml` file to include it as a dependency and then follow [build](https://github.com/cloudfoundry/nodejs-buildpack#building) instructions for generating a buildpack.

Let us know if you have any further questions.

**Comment by liujul** [comment]
Thank you @jtarchie ! 
I have built the binary with Intl. I am going to edit manifest.yml file to include the binary as a dependency. How can I upload my binary to the amanzonaws, so that I can have my own URI? 

  - name: node
    version: 0.12.7
    uri: https://pivotal-buildpacks.s3.amazonaws.com/node/binaries/node-v0.12.7-linux-x64.tar.gz
    md5: 182175d82395171f299e3a05a2ce70a1
    cf_stacks:
      - cflinuxfs2

**Comment by jtarchie** [comment]
@liujul, we host all our binaries on a cloud foundry s3 bucket. We are unable to provide access for you to it. However, you can host it on any publicly available HTTP/S server, so you are not limited to AWS S3.

**Comment by flavorjones** [comment]
@liujul It sounds like @jtarchie was able to point you in the right direction, so I'm going to close this issue out. Please ping me if you'd like to reopen the conversation!

Thanks for using Cloud Foundry!
