### ISSUE TITLE
How to increase request-response timeout

### ISSUE THREAD

**Issue by charyorde** [cloudfoundry/nodejs-buildpack#30]
Hi,

I'm not sure if this is a buildpack or gorouter/ha_proxy issue. However, I would like to give more time to my app to send a response to the requests before getting a timeout.  When the app is taking time to send a response (say 3 mins), I get a 502 from CF.

Any ideas please?

**Comment by jtarchie** [comment]
@charyorde this is not a buildpack issue. Cloud Foundry has timeout on a request if no data has been sent to it in a particular amount of time. I believe it is a value that is set on the deployment of CF, not something customizable on an application level. Contact support of your CF provider for more help.

Kind Regards,

JT
