### ISSUE TITLE
Support for web/reverse proxy

### ISSUE THREAD

**Issue by charyorde** [cloudfoundry/nodejs-buildpack#33]
Hi,

I'm not sure why the node-http-proxy web proxy module doesn't work on CF. I'm using a rule-based proxy redirect as seen at `https://github.com/strongloop/strong-gateway/blob/master/server/middleware/proxy/index.js` . Somehow this doesn't seem to be working.

Here's the snippet:
```
var express = require('express')
var app = express()
var cors = require('cors')

// start http server
var server = app.listen(process.env.VCAP_APP_PORT, function () {

  var host = server.address().address
  var port = server.address().port

  console.log('Proxying Yookore at http://%s:%s', host, port)

})

// Using strong-gateway's http-proxy wrapper for node-http-proxy
// see https://github.com/strongloop/strong-gateway/blob/master/server/middleware/proxy/index.js
var proxy = require('./strong-gateway/server/middleware/proxy/index')

app.use(cors());
app.use(proxy({
  "rules": [
    "^/auth/v1/(.*)$ http://uas.apps.cf.net/v1/$1 [P]"
}));


// App at http://uas.apps.cf.net/v1
var router = app.Router();
app.use('/v1', router);
router.get('/', function(req, res) {
  return res.status(200).send("Welcome to UAS")
})
```

**Comment by jtarchie** [comment]
@charyorde thanks for the issue. I am not familiar with this library.

Are you able to provide any insight to what is failing for you?

* error message
* log messages
* deployment manifest
* etc

**Comment by charyorde** [comment]
Actually, I got an update from the CF group that app-to-app routing is not possible as this has to explicitly go through CF gorouter. And since I'm trying to implement a reverse proxy for our apps, gorouter does the same, hence, I need to write the app in such a way that it makes use of gorouter reverse proxy.

**Comment by jtarchie** [comment]
@charyorde, if this is go-router related, I am going to close this story then. Please feel free to reopen a new issue if you have other node buildpack related issues.
