### ISSUE TITLE
autoset max_old_space_size

### ISSUE THREAD

**Issue by adrai** [cloudfoundry/nodejs-buildpack#34]
Does it make sense for you to automatically set max_old_space_size ?
Is it possible to use the configured memory value (cf scale)?
the reason / use case: https://github.com/nodejs/node/wiki/Frequently-Asked-Questions

**Comment by aminjam** [comment]
Buildpack users should be able to set the `--max_old_space_size` through the `Procfile` depending on how much memory is allocated at the runtime.

Procfile
```
web: node --max_old_space_size=128 server.js
```
Deploy
```
cf push app -m 128M
```
@davidjahn mentioned that you may also be able to retrieve that information dynamically at the start time depending on your version of CF. I believe the newer ones should all have the `VCAP_APPLICATION` options.

```
web: node --max_old_space_size=$(echo $VCAP_APPLICATION | jq '.limits.mem') server.js
```

**Comment by adrai** [comment]
thanks for the answer

**Comment by afeld** [comment]
> automatically set max_old_space_size

Is this a pull request y'all would consider? Seems like a nice "smart" thing the buildpack could do for users out of the box.

**Comment by flavorjones** [comment]
Hey @afeld,

Great to hear from you!

If you wanted to put in the effort to have the nodejs buildpack "do the right thing" and set this value to the size of the application memory limit at runtime, that would be an interesting thing to consider; but I'd also want to see how it behaves in real-world situations.

I think the real answer here is that nobody has been able to explain (other than the barebones FAQ linked to) that this actually works as intended. See related thread from last July:

> https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/message/OSI4RD4X2FLE2U44SEWLTD66JHZIBWO4/

**Comment by adrai** [comment]
fyi: https://github.com/adrai/chat-example/blob/master/package.json#L13

**Comment by CAFxX** [comment]
Our internal users ran into this today with a 512M memory quota. This should ideally be implemented, but at the very least it should be clearly documented.
