### ISSUE TITLE
garbage being emitted to STDOUT when I attempt to use a version of node that's not supported in the buildpack

### ISSUE THREAD

**Issue by flavorjones** [cloudfoundry/nodejs-buildpack#35]
In buildpack v1.5.1, binary data is emitted to STDOUT if the version of node I'm trying to use isn't in the manifest.

Related, if I try to deploy using `cf push <appname> -b https://github.com/cloudfoundry/nodejs-buildpack`, without a version specified, it similarly will throw up all over itself.

**Comment by Amit-PivotalLabs** [comment]
+1, I just saw this as well.  Here's an app you can use to reproduce:

https://github.com/cloudfoundry-incubator/cf_canaries/tree/f41988ab36a8a7eab4185ab041f01ff4b10b8fec/assets/instances

Here's the line that looks like it's puking:

https://github.com/cloudfoundry/nodejs-buildpack/blob/v1.5.1/lib/binaries.sh#L27

Here's the URL it's trying to "silently" curl:

http://s3pository.heroku.com/node/v0.10.13/node-v0.10.13-linux-x64.tar.gz

I can wget that URL just fine, and it untars normally, so I'm not sure why staging is failing.  It might actually be that all that garbage output is breaking something.

**Comment by flavorjones** [comment]
We should have a fix for this today.

**Comment by flavorjones** [comment]
This was fixed in v1.5.2 of the buildpack.
