### ISSUE TITLE
Missing versions in files/versions.json

### ISSUE THREAD

**Issue by rndstr** [cloudfoundry/nodejs-buildpack#38]
Shouldn't the 4.x.y versions be added there as well?

I'm trying to deploy an application that has `engines.node: "4.2.x"` in the `packages.json`.

[bin/generate_versions](https://github.com/cloudfoundry/nodejs-buildpack/blob/master/bin/generate_versions) seems to download 4.x, so [compile-extensions#bin/is_cached](https://github.com/cloudfoundry/compile-extensions/blob/master/bin/is_cached) returns true but the [lib/version_resolver.js](https://github.com/cloudfoundry/nodejs-buildpack/blob/master/lib/version_resolver.js) gives `undefined` since it only checks [files/versions.json](https://github.com/cloudfoundry/nodejs-buildpack/blob/master/files/versions.json) where only <=0.12.x are listed

**Comment by flavorjones** [comment]
Hi @rndstr,

Thanks for asking. I'd like to better understand what you're doing, as 4.2 is supported in the latest nodejs buildpack, [v1.5.3](https://github.com/cloudfoundry/nodejs-buildpack/releases/tag/v1.5.3).

Are you using your CF installation's default nodejs buildpack? If so, can you reply with the output from runing `cf buildpacks`?

Are you passing a git URL for a buildpack option at push time (e.g. `cf push appname -b https://github.com/cloudfoundry/yada/yada`)? If so, can you provide the command line you're using?

Thanks!

**Comment by rndstr** [comment]
Hey @flavorjones, thanks for the quick response. We are using v1.5.2 (which is supporting 4.2 as well).

```
 $ cf buildpacks
Getting buildpacks...
buildpack                            position   enabled   locked   filename   
<snip>
nodejs_buildpack                     5          true      false    nodejs_buildpack-cached-v1.5.2.zip   
<snip>
```

I'm not providing a buildpack URL.

Here is the output where it fails finding the nodejs version:

```
-----> Installing binaries
       engines.node (package.json):  4.2.x
       engines.npm (package.json):   unspecified (use default)
       Resolving node version 4.2.x via semver.io...
       Downloading and installing node undefined...
       Downloaded []
       Unable to download node undefined; does it exist?
```

I forgot to mention the file where the call originiates, in [lib/binaries.sh](https://github.com/cloudfoundry/nodejs-buildpack/blob/0de857c8a09f2807503e10c97c33be9e45e4f4b4/lib/binaries.sh#L10-L32). It doesn't actually call semver.io because it's cached.

If you call `node lib/version_resolver.js "4.2.x"` yourself, it returns undefined, since `versions.json` is out of date.

And here the output with modified engine as node 0.12.x

```
----> Installing binaries
       engines.node (package.json):  0.12.x
       engines.npm (package.json):   unspecified (use default)
       Resolving node version 0.12.x via semver.io...
       Downloading and installing node 0.12.7...
       Downloaded [file:///var/vcap/data/dea_next/admin_buildpacks/072ef887-2ba2-44c2-a72d-e9fbb604a2d3_564637e3a4adc3a4b0efc22bc801d6f3c5c7185c/dependencies/https___pivotal-buildpacks.s3.amazonaws.com_node_beta-binaries_node-0.12.7-linux-x64.tar.gz]
       Using default npm version: 2.11.3
```

I also just stumbled upon the [Coding Guidelines](https://github.com/cloudfoundry/nodejs-buildpack/blob/master/CONTRIBUTING.md)

`If a new version of node is added to the manifest.yml it must be added to files/versions.json.`

So I'll go ahead and try to create a PR

**Comment by rndstr** [comment]
thanks @aminjam

**Comment by Dannyzen** [comment]
Hey, this will be in the 1.5.4 release - expected later today
