### ISSUE TITLE
Integration tests should stop hard-coding node versions where possible

### ISSUE THREAD

**Issue by menehune23** [cloudfoundry/nodejs-buildpack#382]
When we update the versions of node provided by this buildpack, a number of tests inevitably fail and require manual updates. This is due to the hard-coding of node versions in tests. Instead, we should make the tests "smarter" and use the information provided by the buildpack manifest to assert expected node versions.

For example, in testing that the default version of node is used during a test, we should lookup the `node` entry from `default_versions` and use that in the test assertions, instead of hard-coding `16`.

Additionally, there are many fixtures that specify a Node engine version within `package.json` which can be loosened/omitted, to keep from having to manually update.

**Comment by ryanmoran** [comment]
Closing as low-priority.
