### ISSUE TITLE
The nodejs-buildpack support node version

### ISSUE THREAD

**Issue by chiacchang** [cloudfoundry/nodejs-buildpack#39]
The buildpack raised error when bump the version up to 4.0.0.

There's a thrid party buildpack

http://jamesthom.as/blog/2015/09/18/node-dot-js-v4-in-cloud-foundry/

I hope there's someone in CF would come up an official version soon. ES6 needed!

**Comment by aminjam** [comment]
@chiacchang We are now supporting Node 4.2.x in [our buildpack](https://github.com/cloudfoundry/nodejs-buildpack/blob/master/manifest.yml). What error are you seeing when using Node 4.2.x?

**Comment by chiacchang** [comment]
Thanks, @aminjam  After specify the repo url in the cf push, I'm now even able to get the buildpack working.
