### ISSUE TITLE
Please support Node.js 5.2.0

### ISSUE THREAD

**Issue by mastertinner** [cloudfoundry/nodejs-buildpack#40]

**Comment by Dannyzen** [comment]
Hey @mastertinner thanks for the feedback. Our [1.5.4](https://github.com/cloudfoundry/nodejs-buildpack/releases/tag/v1.5.4 "1.5.4") was the first to support 5.x releases. As 5.2 just came out yesterday we've prioritized it accordingly. With that said, if you'd like insight into our prioritization, please take a look at our [Backlog.](https://www.pivotaltracker.com/n/projects/1042066 "Backlog")
