### ISSUE TITLE
How to perform integration test using nodejs-buildpack?

### ISSUE THREAD

**Issue by Nibedita-Udvavisk** [cloudfoundry/nodejs-buildpack#400]
Hello,
I have deployed my node.js application on cloudfoundry. While deploying an application by default it will run "npm start" from package.json module.

I want to perform integration test using "jest", so I have 'npm test' script in my package.json module. 
ex: "test": "jest --verbose --detectOpenHandles"

So, my question is that how to run the application on cloudfoundry to run the application in test mode?

Is by setting environment variable for cloudfoundry will run npm test command?
or  I have to specify the test script value in start script?
like, "start": "jest --verbose --detectOpenHandles"

**Comment by ryanmoran** [comment]
This isn't really a usecase that we actively support. You may be able to do this with the modifications to the start command that you are suggesting, but we haven't actively tried that. Closing as unsupported.
