### ISSUE TITLE
AppDynamics Service - Unclear on the extension

### ISSUE THREAD

**Issue by pkumar-appd** [cloudfoundry/nodejs-buildpack#41]
For AppDynamics service, in case of nodejs-buildpack I need to access system variables. So that the application can be monitored on AppDynamics Controller.

Do we need to add an extension file. What language should i prefer to write an extension for NodeJs-Buildpack.

**Comment by jtarchie** [comment]
You can write it in any language that is supported via the rootfs. Usually the buildpacks are written in `bash`, but we natively support `ruby` and `python`. As long as the script is executable, the buidlpack does not care what language it is written in.
