### ISSUE TITLE
npm 8.x.x support

### ISSUE THREAD

**Issue by milkotodorov** [cloudfoundry/nodejs-buildpack#416]
In the current version of the buildpack npm version 6.14.15 is used.
Why the npm 8.x.x is not supported?

**Comment by raulfdm** [comment]
(curiosity) does it work if you specify in the engines in your package.json?

```json
"engines": {
  "npm": "8.0.0"
}
```

**Comment by brayanhenao** [comment]
Hi @milkotodorov 

The `NodeJS Buildpack` uses the default NPM version listed in the official NodeJS [`releases page`](https://nodejs.org/en/download/releases/) for every Node version.

For the latest version of the `NodeJS Buildpack` (v1.7.67) the following are the versions of Node with their respective default version of NPM:

| Buildpack Node Version  | Buildpack default NPM version |
| ------------- | ------------- |
| v12.22.9 | v6.14.15 |
| v12.22.10 | v6.14.16 |
| v14.18.2 | v6.14.15 |
| v14.19.0 | v6.14.16 |
| v16.13.1 | v8.1.2 |
| v16.14.0 | v8.3.1 |


However, as @raulfdm posted

> (curiosity) does it work if you specify in the engines in your package.json?
> 
> ```json
> "engines": {
>   "npm": "8.0.0"
> }
> ```

You can specify an explicit version of NPM for your app in your `package.json`
