### ISSUE TITLE
[ERR] at Object.mkdirSync (node:fs:1334:3) nodejs 1.7.63

### ISSUE THREAD

**Issue by spkrsna** [cloudfoundry/nodejs-buildpack#424]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
>cf curl /v2/info
{
   "name": "Pivotal Application Service",
   "build": "2.7.45-build.1",
   "support": "https://support.pivotal.io",
   "version": 0,
   "description": "https://docs.pivotal.io/pivotalcf/2-7/pcf-release-notes/runtime-rn.html",
   "min_cli_version": "6.23.0",
   "min_recommended_cli_version": "6.23.0",
   "api_version": "2.139.0",
   "osbapi_version": "2.15",
   
}

What version of the buildpack you are using?

nodejs 1.7.63

If you were attempting to accomplish a task, what was it you were attempting to do?

to push an app
What did you expect to happen?
to up and run

What was the actual behavior?
crashing

Can you provide a sample app?
 [CELL/0] [OUT] Downloading droplet...
 [CELL/0] [OUT] Downloaded droplet (54.6M)
 [APP/PROC/WEB/0] [ERR] node:fs:1334
 [APP/PROC/WEB/0] [ERR] handleErrorFromBinding(ctx);
 [APP/PROC/WEB/0] [ERR] ^
 [APP/PROC/WEB/0] [ERR] Error: EACCES: permission denied, mkdir '/usr/share/
 [APP/PROC/WEB/0] [ERR] at Object.mkdirSync (node:fs:1334:3)
[APP/PROC/WEB/0] [ERR] at /home/vcap/app/node_modules/file-stream-rotator/FileStreamRotator.js:654:20
 [APP/PROC/WEB/0] [ERR] at Array.reduce (<anonymous>)

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by brayanhenao** [comment]
Hi @spkrsna could you please share the steps to reproduce the error, and if possible, a sample application.

**Comment by brayanhenao** [comment]
Closed after +3 months of no replies.
