### ISSUE TITLE
Re-create as Non-Forked Repo?

### ISSUE THREAD

**Issue by TuckerWhitehouse** [cloudfoundry/nodejs-buildpack#44]
I'm curious if there is any continued benefit to being a fork of heroku-buildpack-nodejs.
My biggest complaint is that GitHub does not support Code Search for Forked repos, and from what I can see, the two buildpacks are quite different at this point.

**Comment by jtarchie** [comment]
Heroku has done a great job at maintaining the buildpack in relation to the `nodejs` and `npm` community standards. Our fork adds support for the security policies for limiting versions and working in air-gapped environments.

What source were you looking for?

**Comment by TuckerWhitehouse** [comment]
It's difficult to determine when something is part of the original buildpack or included in the 5,185 additions in the Cloud Foundry version: https://github.com/heroku/heroku-buildpack-nodejs/compare/master...cloudfoundry:master

**Comment by jtarchie** [comment]
They do diverge, but additions have, hopefully, been non-invasive to the functionality that Heroku still provides with their open source buildpack. That is a different issue, though, from being able to search from Github search.

Is there a particular section of code that you have a question about?

**Comment by TuckerWhitehouse** [comment]
I have been able to find all of my answers by just browsing the code, but there have been multiple times that I have had a question and my immediate reaction was to try and search the Cloud Foundry buildpack on GitHub, and could not.
