### ISSUE TITLE
[QUESTION] Which NodeJs buildpack version is used

### ISSUE THREAD

**Issue by mikolasz** [cloudfoundry/nodejs-buildpack#462]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
cf version 6.53.0+8e2b70a4a.2020-10-01

What version of the buildpack you are using?
1.7.69

If you were attempting to accomplish a task, what was it you were attempting to do?
cf deploy <mtarfile>.mtar
deploying the approuter of an MTA Java based CAP application.
using parameter in the mta.yaml:  
nodejs-buildpack: nodejs_buildpack
![image](https://user-images.githubusercontent.com/46314078/174539925-7fc377e5-0b8f-4b39-a5fe-037598e0a96a.png)

What did you expect to happen?
Downloading the latest release buildpack

What was the actual behavior?
Downloading the 1.7.69 nodejs-buildpack

Can you provide a sample app?
https://github.tools.sap/Concur-MBS/auditportal

Log:
[auditportal-approuter.log](https://github.com/cloudfoundry/nodejs-buildpack/files/8938131/auditportal-approuter.log)

Please confirm where necessary:
* [X] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**My question:**
What exactly affects that which nodejs-buildpack version will be downloaded?
I know that I can use an exact version in the mta.yaml like this:
`nodejs-buildpack: https://github.com/cloudfoundry/nodejs-buildpack.git#v1.7.65`
but if I only use `nodejs-buildpack: nodejs_buildpack` why the 1.7.69 is downloaded and not the latest release? (`1.7.71`)

**Comment by brayanhenao** [comment]
Closed after +3 months of no replies.
