### ISSUE TITLE
When will the default node version change?

### ISSUE THREAD

**Issue by marikaner** [cloudfoundry/nodejs-buildpack#519]
I am from the [SAP Cloud SDK](https://sap.github.io/cloud-sdk), a library that can be used on CF, specifically using the node buildpack, to build applications in the SAP ecosystem.
We are currently planning our next major version release and want to support the current default version of the CF node buildpack.
In two weeks node 18 will become the active LTS version (see [here](https://github.com/nodejs/Release)), so it would make sense to upgrade the default version at some point.

Are there any plans when the CF node buildpack will move to node 18 as a default? I couldn't find this information in the documentation.

**Comment by brayanhenao** [comment]
Hi @marikaner. Nodejs `18.x` will be the default node version in the next release cadence (around the first week of November).

**Comment by marikaner** [comment]
Hi @brayanhenao, I just checked an the default version is still node 16. I can see that it is 18 on `develop`. Do you know when this should be released?
