### ISSUE TITLE
manifest option for selecting engines.node latest version?

### ISSUE THREAD

**Issue by SimyungYang** [cloudfoundry/nodejs-buildpack#55]
each node buildpacks has different node version supports like the followings.

```
The versions of node supported in this buildpack are:
- 4.2.2
- 0.12.7
- 0.12.6
- 0.11.16
- 0.11.15
- 0.10.40
- 0.10.38
```

I am wondering if there is any option to select just latest node version in buildpack.
Now according to my test result, it seems like default node version is not the latest.

the problem is when I update the node buildpack.
it node apps doesn't apply this key, all node apps running on my cf should be changed their package.json configuration.

Please let me know. Thank you :)

**Comment by Dannyzen** [comment]
Hi @SimyungYang Thanks for putting in an issue. When you say "latest" version this can be complicated as node has [many version lines](https://github.com/nodejs/LTS/blob/master/schedule.png). 

What this buildpack does is enable the end-user to choose a major version line and then receive the latest version within that version line. See [this fixture app](https://github.com/cloudfoundry/nodejs-buildpack/blob/master/cf_spec/fixtures/node_web_app_with_version_range/package.json#L16) as an example.

I should note that the versions you've pasted into this issue do not match the current versions supported in [recent versions of this buildpack](https://github.com/cloudfoundry/nodejs-buildpack/releases), so you may want to upgrade.

Please re-open this issue if you need more help or clarification.
