### ISSUE TITLE
Release: nodejs-buildpack (Feb)

### ISSUE THREAD

**Issue by arjun024** [cloudfoundry/nodejs-buildpack#556]
Release reminder!
Also, make sure you pull in the `Release Reminder` workflow before release so that it automates this issue creation!

**Comment by ryanmoran** [comment]
Blocked on: https://nodejs.org/en/blog/vulnerability/february-2023-security-releases/

**Comment by ryanmoran** [comment]
No longer blocked. The security releases are out. Please confirm this release contains the patched Node.js versions.

**Comment by sophiewigmore** [comment]
https://github.com/cloudfoundry/nodejs-buildpack/releases/tag/v1.8.6
