### ISSUE TITLE
Support for Node Version 0.10.33

### ISSUE THREAD

**Issue by AnandiY** [cloudfoundry/nodejs-buildpack#56]
Kindly include the Node Engine version 0.10.33 in this build pack.
Kindly add the respective entries in the manifest.yml at the earliest possible.

**Comment by Dannyzen** [comment]
Hi @AnandiY. Thanks for submitting an issue. Our project policy is to support n-1 versions of LTS release. As the current version at the time of this response is 0.10.44 we cannot include 0.10.33. 

I should note that there have been several CVE fixes in place to patch security holes from 0.10.33 to 0.10.44. 

Finally, it looks as though you have forked the buildpack and [included 0.10.33](https://github.com/AnandiY/CustonNodeBuildPackTest/blob/master/manifest.yml#L22) in your fork.

Please let us know if we can help you further.

**Comment by AnandiY** [comment]
Thanks for the response Dannyzen.
As I needed the particular version of node for our app, I had submitted that query.
As you said, I have added the node version **0.10.33** in my copy of the NodeJSBuildpack.

**Comment by jvshahid** [comment]
Hey @AnandiY, I'm interested in knowing why you have to lock the app to a specific version of node.

**Comment by AnandiY** [comment]
Hi jvshahid, certain node modules used in the app are compatible with the particular node version only.

**Comment by flavorjones** [comment]
@AnandiY can you be more specific? What's the name of the module you're having trouble with? What are the error messages you're seeing when running with node 0.10.44, and when do you see them?

My understanding is that Node does a great job of making sure all point releases are backwards-compatible, so it would surprise me to learn that a module would work with 0.10.33 but break with 0.10.44.
