### ISSUE TITLE
Release: nodejs-buildpack (Mar)

### ISSUE THREAD

**Issue by cf-buildpacks-eng** [cloudfoundry/nodejs-buildpack#573]
Release reminder for nodejs-buildpack

* See [diff from latest version](https://github.com/cloudfoundry/nodejs-buildpack/compare/v1.8.6..develop) and validate if a release is required.
* Make sure the latest commit on  has passed tests on the [CI](https://buildpacks.ci.cf-app.com/teams/main/pipelines/nodejs-buildpack)
* Refer [release instructions](https://github.com/pivotal-cf/tanzu-buildpacks/wiki/Releasing-CF-Buildpacks). (private link)

**Comment by brayanhenao** [comment]
https://github.com/cloudfoundry/nodejs-buildpack/releases/tag/v1.8.7
