### ISSUE TITLE
Removal of node.js 14 from the nodejs-buildpack

### ISSUE THREAD

**Issue by AnnaAAL** [cloudfoundry/nodejs-buildpack#577]
Since Node.js 14 is reaching EoL on 31st April, could you advise when it's planned to be removed from the nodejs-buildpack? Thank you.

**Comment by ryanmoran** [comment]
30 days before the EOL date, the buildpack will start to warn that v14 will be removed. On or after the EOL date, the buildpack will be removed. You can expect it to be gone in the first release published after that date.
