### ISSUE TITLE
RFC: Removing ability to specify npm version

### ISSUE THREAD

**Issue by Dannyzen** [cloudfoundry/nodejs-buildpack#58]
Hi there!

It was recently brought to our attention in issue https://github.com/cloudfoundry/nodejs-buildpack/issues/54 that the nodejs buildpack attempts to download npm if the version specified in package.json does not match the version shipped with nodejs. According to [heroku](https://devcenter.heroku.com/articles/nodejs-support#specifying-an-npm-version) this feature exists for historical reasons that no longer apply. We would like to remove this functionality, specifically for use in offline environments and plan on scheduling work on 4/25.

If you rely on this feature or have an objection to this change please let us know.

**Comment by tomoe** [comment]
Hi,

The link to the tracker redirects me to "https://www.pivotaltracker.com/not_allowed". Is it possible to make it publicly readable? 

Thanks,
Tomoe

**Comment by flavorjones** [comment]
@tomoe - I believe in this case you're getting this error because the story was deleted. And I believe the story was deleted because it's not relevant -- because this is an RFC, all commentary and conversation is  (should be) happening in this GitHub Issue.

What additional context are you looking for? Do you have questions?

(I'm going to edit the cf-gitbot comment above to reflect the facts I'm posting.)

**Comment by jvshahid** [comment]
For completeness, Shawn on the [cf-dev mailing list](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/ZRSOFXISIR4PHWIRFN4RABBRAGE42VZR/#ZRSOFXISIR4PHWIRFN4RABBRAGE42VZR) had a valid use case for keeping the capability of specifying different npm versions:

>  We have had a few use cases where users have requested to stay on nodejs version 4 (LTS), while taking advantage of npm 3's new flat dependency tree. Node 4 by default bundles witn npm 2. Node 5 defaults to npm 3. In all of these use cases we are using online buildpacks. I would say this use case isn't as common, but we definitely get requests for it.

@flavorjones @dmikusa-pivotal what about documenting that if you are in an offline environment then you should not override the npm version ? is this an acceptable solution ?

**Comment by tomoe** [comment]
@flavorjones, 

>  I believe in this case you're getting this error because the story was deleted. And I believe the story was deleted because it's not relevant -- because this is an RFC, all commentary and conversation is (should be) happening in this GitHub Issue.

Thanks for following up.  I wonder if I should've gotten not found (or 404) in that case, though, but it's not really important :-) 

> What additional context are you looking for? Do you have questions?

I was curious to know where this is going (what and when this change would happen), but it looks like this is not going to happen as per the email list conversation. So, I am good now. Thanks!

**Comment by jvshahid** [comment]
@tomoe the reason behind this issue is to start a conversation with users of the buildpack to understand their use cases and whether this change is desired or not. Is this a change that you are for or against and why ?

**Comment by tomoe** [comment]
@jvshahid Looks like this proposal is going to be retracted because of the response in the email list. I am all for it. 
I think this issue is now good to be closed.
