### ISSUE TITLE
Ruby is not available in cflinuxfs4

### ISSUE THREAD

**Issue by ryanmoran** [cloudfoundry/nodejs-buildpack#584]
The buildpack includes a [setup script for AppDynamics](https://github.com/cloudfoundry/nodejs-buildpack/blob/b0f056873f79b9a7695edc844239cd6fd19dc9e7/profile/appdynamics-setup.rb) that relies upon Ruby being available. Since `cflinuxfs4` has removed Ruby from the stack, this setup script will not be able to run.

The buildpack will need to either bring along its own Ruby or be rewritten to not rely upon an installed Ruby for these operations.

**Comment by robdimsdale** [comment]
Note - if we decide to bootstrap ruby, we should bootstrap it into `/tmp/<buildpack-name>/ruby`, not `/tmp/ruby`.

There are situations where multiple buildpacks attempt to bootstrap ruby into the same location at `/tmp/ruby`. This may be causing non-deterministic issues, so to be safe we should bootstrap into `/tmp/<buildpack-name>/ruby`.

See example of bootstrapping ruby into buildpack-specific namespace: https://github.com/cloudfoundry/php-buildpack/pull/855

**Comment by arjun024** [comment]
Also needs #607
