### ISSUE TITLE
Python is not available on the cflinuxfs4 stack

### ISSUE THREAD

**Issue by ryanmoran** [cloudfoundry/nodejs-buildpack#585]
The `cflinuxfs4` stack no longer includes Python and this has a negative impact on `node-gyp`-built dependencies which may require that a Python be available. An example of this type of application can be found here: https://github.com/Gerg/gyp-app

We will need to include a Python into the build phase only so that these types of dependencies can be built.

**Comment by sophiewigmore** [comment]
Done by PR above and released in https://github.com/cloudfoundry/nodejs-buildpack/releases/tag/v1.8.8
