### ISSUE TITLE
Release: nodejs-buildpack (Apr)

### ISSUE THREAD

**Issue by cf-buildpacks-eng** [cloudfoundry/nodejs-buildpack#590]
Release reminder for nodejs-buildpack

* See [diff from latest version](https://github.com/cloudfoundry/nodejs-buildpack/compare/v1.8.8..develop) and validate if a release is required.
* Make sure the latest commit on  has passed tests on the [CI](https://buildpacks.ci.cf-app.com/teams/main/pipelines/nodejs-buildpack)
* Refer [release instructions](https://github.com/pivotal-cf/tanzu-buildpacks/wiki/Releasing-CF-Buildpacks). (private link)

**Comment by brayanhenao** [comment]
[v1.8.9](https://github.com/cloudfoundry/nodejs-buildpack/releases/tag/v1.8.9) Released
