### ISSUE TITLE
Offline buildpack still downloading files

### ISSUE THREAD

**Issue by ArthurHlt** [cloudfoundry/nodejs-buildpack#6]
I'm currently using the offline buildpack on my own cloudfoundry instance and i ran `npm install` before pushing my app to have all my dependencies already in the app. But when the app staging the compilation run `npm rebuild` and this command go to download nodejs source (i don't know why) from internet which is pretty annoying when you are offline :) 
I know that the `compile` script come from heroku but Is there a way to make it not download nodejs source?

Recreate the issue by following this instruction for example:
 1. Download [https://github.com/cloudfoundry-community/etherpad-lite-cf/releases/download/1.4.0-cf/etherpad-lite-cf.zip](https://github.com/cloudfoundry-community/etherpad-lite-cf/releases/download/1.4.0-cf/etherpad-lite-cf.zip) (this is a nodejs app which already set for being offline)
 2. Extract the archive
 3. go to extracted archive
 4. push the app
 5. In log we can see `http get` from npm

**Comment by jtarchie** [comment]
We were able to recreate the issue in our local testing environment with an offline CF. It turns that `npm` and `node-gyp` are not well suited for an offline environment.

When it comes to compiling dependencies we cannot guarantee that they will not make calls to the Internet. The offline-buildpack is only able to make sure that `nodejs` and `npm` are installed correctly in an offline environment.

We'd have to make internal changes to `npm` to support a true offline buildpack, which at this time is beyond the scope of the buildpack team. The topic of extending `npm` was discuss [here](https://github.com/cloudfoundry/nodejs-buildpack/pull/11).
