### ISSUE TITLE
supporting FIPS Node.js builds

### ISSUE THREAD

**Issue by opiethehokie** [cloudfoundry/nodejs-buildpack#60]
More of a question than an issue. I'm wondering if there's any plan to do something in the buildpack for FIPS builds? I think someone building the buildpack themselves and adding FIPS builds to the manifest.yml would run into a couple of issues.

1) One is wanting to have two node binaries in manifest.yml with the same version, say 6.0.0. One is the FIPS build and one is the non-FIPS build. The app developer needs a way to select between them, like a new environment variable?

2) The other is turning FIPS mode on/off when using the FIPS build. One way to do this is with the [--enable-fips](https://nodejs.org/api/cli.html#cli_enable_fips) command-line option, so it could definitely be left to the app developer to include in their app's start command. The question is basically should the buildpack automatically do this if the FIPS build is selected, or leave it to the app developer to control?

Any thoughts on this?

**Comment by flavorjones** [comment]
See related #47
