### ISSUE TITLE
Release: nodejs-buildpack (May)

### ISSUE THREAD

**Issue by cf-buildpacks-eng** [cloudfoundry/nodejs-buildpack#606]
Release reminder for nodejs-buildpack

* See [diff from latest version](https://github.com/cloudfoundry/nodejs-buildpack/compare/v1.8.9..develop) and validate if a release is required.
* Make sure the latest commit on  has passed tests on the [CI](https://buildpacks.ci.cf-app.com/teams/main/pipelines/nodejs-buildpack)
* Refer [release instructions](https://github.com/pivotal-cf/tanzu-buildpacks/wiki/Releasing-CF-Buildpacks). (private link)

**Comment by arjun024** [comment]
Blocking on #605

**Comment by brayanhenao** [comment]
Blocking on 14.x deprecation #601

**Comment by arjun024** [comment]
Please wait until I figure out why brats is failing since #605

**Comment by brayanhenao** [comment]
[v1.8.10](https://github.com/cloudfoundry/nodejs-buildpack/releases/tag/v1.8.10) Released.
