### ISSUE TITLE
Deployment to BTP fails when Node is upgraded to v16.20.1

### ISSUE THREAD

**Issue by sidhartha31** [cloudfoundry/nodejs-buildpack#622]
Hi Colleagues,

We are trying to fix a security vulnerability https://cdrc-tools-ngt.wdf.global.corp.sap/scns/api/scns/SCN-2023-13259/v1 and for that, we need to upgrade Node version to v16.20.1

What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
8.4.0

What version of the buildpack you are using?
1.8.11

If you were attempting to accomplish a task, what was it you were attempting to do?
Upgrading Node version to v16.20.1

What did you expect to happen?
Node v16.20.1 should have been downloaded during application deployment to SAP BTP using NodeJS buildpack.

What was the actual behavior?
Got an error message:  **ERROR** Unable to install node: no match found for 16.20.1 in [14.21.2 14.21.3 16.19.1 16.20.0 18.14.1 18.15.0]

Can you provide a sample app?
Application is unable to deploy.

<img width="950" alt="Error" src="https://github.com/cloudfoundry/nodejs-buildpack/assets/14909953/55900cbe-040d-44f7-9e0e-ccddb9fe0db6">

Please confirm where necessary:
* [X] I have included a log output
* [X ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by sidhartha31** [comment]
Hi Colleagues,
Can I please get an update on this?

**Comment by arjun024** [comment]
16.20.1 didn't go out with the previous release due to a pipeline glitch. It should be in the upcoming version (see #623)
Feel free to reopen the issue for any further communication
