### ISSUE TITLE
preinstall not always running on cf push

### ISSUE THREAD

**Issue by plindberg** [cloudfoundry/nodejs-buildpack#63]
### What version of Cloud Foundry are you using?

cf version 6.19.0+b29b4e0-2016-06-08

### What version of the buildpack you are using?

I have reproduced this on IBM SDK for Node.js Buildpack v3.4-20160518-1653 which is based on Node.js Buildpack v1.5.4, as well as on version 1.5.15 which Pivotal uses.

### If you were attempting to accomplish a task, what was it you were attempting to do?

To run a npm preinstall script which installs my GitHub deploy key in ~/.ssh while also specifying node version.

### What did you expect to happen?

That the preinstall script would run.

### What was the actual behavior?

It doesn’t run when I specify a node version. But if I remove the line specifying node version, the preinstall script runs just fine. The error I get when a node version is specified is that npm can’t clone the private GitHub repo in the dependences, which wouldn’t happen if the preinstall script had run.

### To reproduce:

```json
{
 "name": "test",
 "version": "0.0.1",
 "scripts": {
   "preinstall": "echo PREINSTALL"
 },
 "dependencies": {
   "convoflow": "github:monieshq/convoflow"
 },
 "engines": {
   "node": "5.11.1"
 }
}
```

The convoflow dependency is just a private GitHub repo. It needs to be there to reproduce the bug.

When running cf push with the above package.json, it doesn’t echo PREINSTALL.

Remove either the "node" line or the entire "engines" part, and it runs the preinstall script.

### Additional comments

I have reported this to IBM Bluemix and Pivotal. Pivotal suggested it should be reported here.

Please confirm where necessary:
* [ ] I have included a log output 
* [ ] My log includes an error message 
* [x] I have included steps for reproduction

**Comment by plindberg** [comment]
Edited to specify buildpack version on Pivotal.

**Comment by ForestEckhardt** [comment]
@plindberg we recreated the issue and found that with node v5.11.1 if your environment doesn't have access to the git repo, the preinstall command won't run. This is not the case with v4.4.5 which is a more stable version. 

Can you [vendor your dependencies](https://docs.cloudfoundry.org/buildpacks/node/index.html#vendoring)? that way you won't have to push your GitHub deploy keys. 

We'll look into why newer versions of node don't run preinstall commands as expected.

**Comment by ForestEckhardt** [comment]
@plindberg so after further research we have discovered that this is an [open bug with npm v3x] (https://github.com/npm/npm/issues/10379). Node version 5&6 use npm v3x which is why you are encountering this issue.

**Comment by RochesterinNYC** [comment]
Closing as this is an issue with npm `v3.x`.

**Comment by coryjett** [comment]
Just wondering, did you find a workaround for this?  The only way we've gotten around this is by specifying an older version of NPM.  You could do `npm run preinstall` and then `npm install` but not sure how you'd pull that off in Cloud Foundry.

  "engines": {
    "node": "^6.x",
    "npm" : "2.15.5"
  },
