### ISSUE TITLE
About New Relic, we can not disable installing it.

### ISSUE THREAD

**Issue by patapata23** [cloudfoundry/nodejs-buildpack#66]
In order to test in the same environment with the nodejs-buildpack in concourse CI, we create the docker image including the nodejs-buildpack.
While executing the compile command, The following error was occurred in our concourse CI.
```
-------> Buildpack version 1.5.19
/tmp/buildpack/lib/vendor/new_relic/install.sh: line 15: VCAP_APPLICATION: unbound variable
```

The enviroment variable VCAP_APPLICATION becomes required from nodejs-buildpack-v1.5.19.
https://github.com/cloudfoundry/nodejs-buildpack/blob/master/bin/compile#L41

New Relic isn't necessary in most environments, so we want to disable it by settings.

**What version of Cloud Foundry are you using?**

**What version of the buildpack you are using?**
nodejs-buildpack-v1.5.19

**If you were attempting to accomplish a task, what was it you were attempting to do?**

**What did you expect to happen?**
I want to test in the same environment with the nodejs-buildpack in concourse CI.

**What was the actual behavior?**
The above error was occurred in our concourse CI.

Please confirm where necessary:
* [ ] I have included a log output 
* [ ] My log includes an error message 
* [ ] I have included steps for reproduction

**Comment by RochesterinNYC** [comment]
@patapata23 can you please explain what it is you're trying to do?

Staging will always have `VCAP_APPLICATION` set as an environment variable (even if it's just an empty hash), so if `VCAP_APPLICATION` is missing, your environment is not truly emulating staging.

**Comment by sclevine** [comment]
To add to that, a number of other buildpacks expect `VCAP_APPLICATION` to be set as well.

Here's a Dockerfile that fully simulates staging and launching: https://github.com/sclevine/cflocal/blob/master/Dockerfile

**Comment by patapata23** [comment]
@RochesterinNYC Thank you for your reply.
I'll trying to excute only unit-test in nodejs-buildpack environment. 
when my envrironment is truly emulating staging envirionment, It will be executed in the order of the detect -> compile -> release .
I'll executing the only compile command in our concourse CI for unit-testing.

Certainly, This Issue is solved by setting the environment variable as you're right.
I want to know why you require New Relic library.

**Comment by RochesterinNYC** [comment]
What do you mean by execute only unit-test? Do you mean you're only trying to execute the unit tests in the nodejs buildpack? i.e. https://github.com/cloudfoundry/nodejs-buildpack/tree/master/cf_spec/unit ?

What exactly are you unit testing?

I'm not sure you what you mean by requiring the New Relic library.

**Comment by patapata23** [comment]
@RochesterinNYC 
> What exactly are you unit testing?
I use this buildpack in Concourse CI, not in CloudFondry environment.
So, there is no VCAP_APPLICATION.

I compile my own app with nodejs-buildpack, then I execute unit-tests in my app.

> I'm not sure you what you mean by requiring the New Relic library.
when  excuting compile, New Relic is  always installed.
I do not know why New Relic is always installed.
Because did not install the New Relic, heroku.
https://github.com/heroku/heroku-buildpack-nodejs/blob/master/bin/compile

**Comment by RochesterinNYC** [comment]
You're using the nodejs buildpack to stage apps on Concourse? If that's the case, I wouldn't refer to these Cloud Foundry buildpacks as generic enough that they can stage any app on any environment. They're attuned to Cloud Foundry and they are Cloud Foundry buildpacks, so you'd need to either fork the buildpack and remove Cloud Foundry specific nuances or alter your staging environment to emulate the Cloud Foundry staging environment.

The NewRelic library is not included as part of the nodejs-buildpack at all. The NewRelic client library is contained in a `newrelic.js` file that users include in their applications. We only have support in the buildpack to set some New Relic environment variables if your app binds to a New Relic service broker. I'm not sure what you're referring to.

**Comment by patapata23** [comment]
@RochesterinNYC 
Your explanation was understanding. And polite reply thanks.
I'll try to test by setting the staging environment in concourseCI.

For NewRelic library, it had been the understanding that I was wrong. I'm sorry.

Thank you very much.
