### ISSUE TITLE
NOTICE: Node.js 0.10 will be removed after October 31, 2016 due to end of LTS

### ISSUE THREAD

**Issue by sclevine** [cloudfoundry/nodejs-buildpack#67]
Hi All,

Long-term support for Node.js 0.10.x provided by the Node.js LTS Working Group will end on October 31, 2016. Therefore, the Node.js 0.10.x binary dependency provided by the Node.js buildpack will no longer be available in the first release of the buildpack made after October 31st. Please adjust your Node.js CF applications to use a supported version of Node.js by that time.

Please see the [Node.js Long-term Support Schedule](https://github.com/nodejs/LTS#lts_schedule) for more detailed information.

Thank you,
Stephen Levine
CF Buildpacks PM

**Comment by sesmith177** [comment]
Node.js 0.10.x binaries have been removed from and will no longer be in the nodejs-buildpack: https://github.com/cloudfoundry/nodejs-buildpack/commit/9b5963a370ad87b811eec2a03a6598b2d611df3a
