### ISSUE TITLE
Release: nodejs-buildpack (Nov)

### ISSUE THREAD

**Issue by cf-buildpacks-eng** [cloudfoundry/nodejs-buildpack#670]
Release reminder for nodejs-buildpack

* See [diff from latest version](https://github.com/cloudfoundry/nodejs-buildpack/compare/v1.8.19..develop) and validate if a release is required.
* Make sure the latest commit on  has passed tests on the [CI](https://buildpacks.ci.cf-app.com/teams/main/pipelines/nodejs-buildpack)
* Refer [release instructions](https://github.com/pivotal-cf/tanzu-buildpacks/wiki/Releasing-CF-Buildpacks). (private link)

**Comment by thitch97** [comment]
Release not required. (see diff linked above)

**Comment by robdimsdale** [comment]
Let's release in order to ensure we're building with the latest version of golang. (Same for all v2b buildpacks)

**Comment by brayanhenao** [comment]
[v1.8.20](https://github.com/cloudfoundry/nodejs-buildpack/releases/tag/v1.8.20) Released.
