### ISSUE TITLE
How to install libsasl2-dev package 

### ISSUE THREAD

**Issue by vmovva** [cloudfoundry/nodejs-buildpack#70]
I am trying to install node module node-rdkafka : https://www.npmjs.com/package/node-rdkafka using latest nodejs buildpack.

my package.json looks like : 

```
{
    "name": "hello-node",
    "version": "0.0.0",
    "dependencies": {
        "cfenv":"^1.0.3",
        "node-rdkafka":"^0.5.5"
    },
    "main": "server.js",
    "scripts": {
        "start": "node server.js"
    }

} 
```

When i push my application, it fails with following exception : 

>  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_sasl.o
>        ../deps/librdkafka/src/rdkafka_sasl.c:35:23: fatal error: sasl/sasl.h: No such file or directory
>        #include <sasl/sasl.h>
>        ^
>        compilation terminated.
>        make: **\* [Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_sasl.o] Error 1
>        make: Leaving directory `/tmp/staged/app/node_modules/node-rdkafka/build'
>        gyp ERR! build error
>        gyp ERR! stack Error:`make` failed with exit code: 2
>        gyp ERR! stack     at ChildProcess.onExit (/tmp/staged/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
>        gyp ERR! stack     at emitTwo (events.js:87:13)
>        gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
>        gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
>        gyp ERR! System Linux 3.19.0-33-generic
>        gyp ERR! command "/tmp/staged/app/vendor/node/bin/node" "/tmp/staged/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
>        gyp ERR! cwd /tmp/staged/app/node_modules/node-rdkafka

I believe it is because Cloudfoundry Ubuntu image does not ship : libsasl2-dev.  

Is there anyway, i can install libsasl2-dev ?

**Comment by RochesterinNYC** [comment]
As you said, `libsasl2-dev` is not currently on the rootfs. There is a story to add it to the rootfs here: https://www.pivotaltracker.com/story/show/130826489

I'd recommend waiting for the completion of that story. Alternatively, you can roll your own rootfs.

**Comment by RochesterinNYC** [comment]
`libsasl2-dev` is now on version `1.89.0` of stacks and up: https://github.com/cloudfoundry/stacks/releases/tag/1.89.0. 

This is incorporated in `v1.38.0` and up of the cflinuxfs2-rootfs-release: https://github.com/cloudfoundry/cflinuxfs2-rootfs-release/releases/tag/v1.38.0
