### ISSUE TITLE
URGENT: go binary missing ? 

### ISSUE THREAD

**Issue by Soontao** [cloudfoundry/nodejs-buildpack#744]
https://github.com/cloudfoundry/nodejs-buildpack/blob/c556da9c4b26f4c0cb3537be6cfcaab101c93cbe/scripts/install_go.sh#L16

```
Manifest applied
Packaging files to upload...
Uploading files...
 7.04 KiB / 7.04 KiB [======================================================================================================================================================================================] 100.00% 1s

Waiting for API to complete processing files...

Staging app and tracing logs...
   Cell 3fd02c15-fc8a-4095-be97-03567e732191 creating container for instance 2ef884d4-e319-4294-b8de-ba865712116f
   Security group rules were updated
   Cell 3fd02c15-fc8a-4095-be97-03567e732191 successfully created container for instance 2ef884d4-e319-4294-b8de-ba865712116f
   Downloading app package...
   Downloaded app package (74.4K)
   -----> Download go 1.19
   **ERROR** SHA256 mismatch: got 24dd6d7b049eb3c2d67395b69c1154ce1b38b8cbc22b56db2e7642235932cfa6, expected 7e231ea5c68f4be7fea916d27814cc34b95e78c4664c3eb2411e8370f87558bd
   Failed to compile droplet: Failed to run all supply scripts: exit status 1
   Exit status 223
   Cell 3fd02c15-fc8a-4095-be97-03567e732191 stopping instance 2ef884d4-e319-4294-b8de-ba865712116f
   Cell 3fd02c15-fc8a-4095-be97-03567e732191 destroying container for instance 2ef884d4-e319-4294-b8de-ba865712116f
BuildpackCompileFailed - App staging failed in the buildpack compile phase
FAILED
```

url: https://buildpacks.cloudfoundry.org/dependencies/go/go_1.19_linux_x64_cflinuxfs3_7e231ea5.tgz 
response: Invalid URL

**Comment by favna** [comment]
We are also facing this issue with several buildpacks. NodeJS and APT. This is seemingly because Broadcom bought VMWare and is now enshitifying the service for everyone who isn't a high roller enterprise service.

**Comment by JoschuaGoetz** [comment]
I am running into the same problem. As a workaround it worked for me to move away from versioned git links for my buildpacks. For some reason those pull go, but just using `nodejs_buildpack` does not pull go. 
At least that was working for the python_buildpack. See cloudfoundry/python-buildpack#937 . Haven't tried with this buildpack.
Might be a solution until they figure this out.

**Comment by ghost91-** [comment]
@favna I'm confused, how is it related to Broadcom/VMWare? AFAIK, Cloud Foundry is managed by the Cloud Foundry Foundation, which is a directed fund of the Linux Foundation. The cloudfoundry.org domain is also owned by the Linux Foundation.

**Comment by ghost91-** [comment]
The Cloud Foundry documentation URL is also broken, by the way... https://docs.cloudfoundry.org/

**Comment by favna** [comment]
@ghost91- My bad. I was under the impression cloud foundry was always part of Pivotal, and therefore VMWare and by recent acquisition Broadcom. I retract my statement.

**Comment by pwasem** [comment]
The download url is still available:

`https://buildpacks.cloudfoundry.org/dependencies/go/go_${version}_linux_x64_cflinuxfs3_${expected_sha:0:8}.tgz`

> E.g <https://buildpacks.cloudfoundry.org/dependencies/go/go_1.19_linux_x64_cflinuxfs3_7e231ea5.tgz> .

But the hash just seems to be wrong!?


```shell
Download go 1.19 **ERROR** SHA256 mismatch: got 24dd6d7b049eb3c2d67395b69c1154ce1b38b8cbc22b56db2e7642235932cfa6, expected 7e231ea5c68f4be7fea916d27814cc34b95e78c4664c3eb2411e8370f87558bd
```

Maybe a caching issue, or a redirect, or yet another supply chain attack?

**Comment by tobiasso85** [comment]
the archive seems to be back again!
just checked:

```sh
shasum -a 256 go_1.19_linux_x64_cflinuxfs3_7e231ea5.tgz | cut -d ' ' -f 1
7e231ea5c68f4be7fea916d27814cc34b95e78c4664c3eb2411e8370f87558bd
```

**Comment by jiangxin0503** [comment]
great

**Comment by Soontao** [comment]
> the archive https://buildpacks.cloudfoundry.org/dependencies/go/go_1.19_linux_x64_cflinuxfs3_7e231ea5.tgz seems to be back again in the "correct" fashion! just checked after downloading it:
> 
> ```shell
> shasum -a 256 go_1.19_linux_x64_cflinuxfs3_7e231ea5.tgz | cut -d ' ' -f 1
> 7e231ea5c68f4be7fea916d27814cc34b95e78c4664c3eb2411e8370f87558bd
> ```
> 
> derived from related [source code](https://github.com/cloudfoundry/nodejs-buildpack/blob/c556da9c4b26f4c0cb3537be6cfcaab101c93cbe/scripts/install_go.sh#L25-L36)

issue solved.

**Comment by Soontao** [comment]
<img width="900" alt="image" src="https://github.com/cloudfoundry/nodejs-buildpack/assets/10473459/7707127c-2b3a-4367-8958-a53f1baf90c5">
happened again now
