### ISSUE TITLE
Bump 22.5.0 to 22.5.1

### ISSUE THREAD

**Issue by nazarkulyk** [cloudfoundry/nodejs-buildpack#752]
Actually nodejs v22.5.0 is broken. Please update release to 22.5.1

**Comment by nazarkulyk** [comment]
More info : https://nodejs.org/en/blog/release/v22.5.1

**Comment by arjun024** [comment]
@nazarkulyk 22.5.1 is already available in https://github.com/cloudfoundry/nodejs-buildpack/releases/tag/v1.8.27
