### ISSUE TITLE
How to create a nodejs buildpack with node-rfc support

### ISSUE THREAD

**Issue by sneha5gsm** [cloudfoundry/nodejs-buildpack#78]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

What version of the buildpack you are using?

If you were attempting to accomplish a task, what was it you were attempting to do?

What did you expect to happen?

What was the actual behavior?

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by sclevine** [comment]
You should be able to include [this node module](https://www.npmjs.com/package/node-rfc) in your package.json without modifying the buildpack

If you're trying to create a private, forked version of the buildpack that includes the SAP NetWeawer RFC Library, you would need to modify the compile script (https://github.com/cloudfoundry/nodejs-buildpack/blob/master/bin/compile) to install that library. Here's more information about how CF buildpacks work that may be useful for this endeavor: https://docs.cloudfoundry.org/buildpacks/custom.html

**Comment by sneha5gsm** [comment]
Thanks a lot Stephen. :)

**Comment by sclevine** [comment]
Happy to help! Closing this for now. Let me know if you have more questions and I can re-open it.
