### ISSUE TITLE
use private NPM registry

### ISSUE THREAD

**Issue by mehrotra-prateek** [cloudfoundry/nodejs-buildpack#79]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

cf api - `2.54.0`
cf cli - `6.17`

What version of the buildpack you are using?
`nodes-1_5_27-fidelity-731d0fd`

If you were attempting to accomplish a task, what was it you were attempting to do?
Instead of vendoring all packages with my application and uploading, I want them to be downloaded at run time from my private registry. Since I am running a private CF, can this be done by updating the copy of build pack we have or is it something that can be done at app level for a CF app.

**Comment by shawn-nielsen** [comment]
We currently run a private registry and allow users to hit it with their
.npmrc file that contains registry configuration pointing to the private
repo.   The .npmrc file can be bundled with the application.

**Comment by sclevine** [comment]
@mehrotra-prateek does the `registry` parameter in `.npmrc` address your issue?

**Comment by mehrotra-prateek** [comment]
Thanks @shawn-nielsen  and @sclevine I will try it and update the status here. .

**Comment by mehrotra-prateek** [comment]
Thanks i am closing this as it works for example apps. Still phantomjs is an issue but for another day.
