### ISSUE TITLE
CWE-494: Download of Code Without Integrity Check

### ISSUE THREAD

**Issue by dotchev** [cloudfoundry/nodejs-buildpack#81]
By default the buildpack uses npm to download dependencies.
npm is known to lack any integrity checks of the downloaded packages.
The downloaded code is executed by the application or by npm if install scripts are present in the packages.

Some might argue that npm is intended to be used only during the build and the downloaded code should be verified before execution.
Still the buildpack downloads the code and executes it right after that without any integrity checks.

At least this security risk should be clearly documented so the users are aware of it.

For reference
http://cwe.mitre.org/data/definitions/494.html

**Comment by sclevine** [comment]
Hi @dotchev,

Thanks for the report!

We document how to vendor node modules here: https://docs.cloudfoundry.org/buildpacks/node/#vendoring

I've prioritized a story to document this CWE in the buildpack docs.

**Comment by dotchev** [comment]
The documentation should highlight that if there are any missing dependencies, the buildpack will download them from the internet using npm install and this has no integrity and authenticity checks so it should be used at user's own risk.
Additionally even if all the dependencies are vendored, the buildpack still runs `npm rebuild` and `npm install` which may result in additional code being downloaded from the internet without verification.

Also it would be good if the buildpack provides some option that guarantees that no additional code is downloaded.

**Comment by dgodd** [comment]
@dotchev I am in the process of documenting this now. A question for you, have you considered yarn? This buildpack supports yarn, and yarn checks sha1 sums. I plan to mention this in the documentation

**Comment by dgodd** [comment]
@sclevine One option for yarn would be to run with the `--frozen-lockfile` flag, which rails if the `package.json` and `yarn.lock` are incompatible (and thus the `yarn.lock` would be updated)

**Comment by sclevine** [comment]
Documented here: https://github.com/cloudfoundry/docs-buildpacks/pull/142

Included a suggestion to use yarn, which does verify downloads. NPM users should not expect to be able to establish a chain of custody, due to complete lack of verification.
