### ISSUE TITLE
What is the nodejs-buildpack license? MIT or Apache V2?

### ISSUE THREAD

**Issue by luisapace** [cloudfoundry/nodejs-buildpack#87]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`? **CF 253**

What version of the buildpack you are using? **1.5.29**

If you were attempting to accomplish a task, what was it you were attempting to do? **N/A**

What did you expect to happen? **that the nodejs-buildpack have only one, determined, license, APACHE or MIT**

What was the actual behavior? **The License file specifies MIT, while the Notice file specifies Apache V2**  

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by sclevine** [comment]
Thanks for the report! Waiting on confirmation from legal before we change LICENSE to Apache.

**Comment by luisapace** [comment]
Hi, any news on that?

**Comment by sclevine** [comment]
Sorry for the delay here, we'll get the files changed ASAP. The buildpack is Apache licensed, with portions under the MIT license.

The NOTICE file will stay the same. The LICENSE file will change to include the Apache license, with a note that portions of the buildpack are under the MIT license.

**Comment by luisapace** [comment]
Thanks a lot!

Best Regards/Cordiali saluti
                                           Luisa Pace

=========================================================================================================================

Ciò che è fuori è anche dentro; e ciò che non è dentro non è da nessuna 
parte. Per questo viaggiare non serve. Se uno non ha niente dentro, non 
troverà mai niente fuori.   È inutile andare a cercare nel mondo quel che 
non si riesce a trovare dentro di sé.  (Tiziano Terzani) 

==========================================================================================================================


Ing.  Luisa Pace
IBM Italy
Bluemix Legal Project Manager 
Via Sciangai, 53  (B1 - 508)
00144 Roma
Italy
Tel. +39.06.5966.3795
Fax. +39.06.5966.3489
mob. +39.335.7368629
e-mail:  luisa_pace@it.ibm.com
